// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.2
// source: file.proto

package filepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileService_Filedowm_FullMethodName          = "/file.fileService/filedowm"
	FileService_LoadFile_FullMethodName          = "/file.fileService/LoadFile"
	FileService_Showfile_FullMethodName          = "/file.fileService/Showfile"
	FileService_Filequeryinfo_FullMethodName     = "/file.fileService/filequeryinfo"
	FileService_ResolveFileHash_FullMethodName   = "/file.fileService/ResolveFileHash"
	FileService_InitMultipart_FullMethodName     = "/file.fileService/InitMultipart"
	FileService_UploadPart_FullMethodName        = "/file.fileService/UploadPart"
	FileService_CompleteMultipart_FullMethodName = "/file.fileService/CompleteMultipart"
	FileService_AbortMultipart_FullMethodName    = "/file.fileService/AbortMultipart"
	FileService_Status_FullMethodName            = "/file.fileService/Status"
	FileService_DeleteFile_FullMethodName        = "/file.fileService/DeleteFile"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileServiceClient interface {
	Filedowm(ctx context.Context, in *ReqFileDown, opts ...grpc.CallOption) (*Resp, error)
	LoadFile(ctx context.Context, in *Reqloadfile, opts ...grpc.CallOption) (*Resp, error)
	Showfile(ctx context.Context, in *Reqshowfile, opts ...grpc.CallOption) (*Resp, error)
	Filequeryinfo(ctx context.Context, in *ReqFileQuery, opts ...grpc.CallOption) (*RespFileQuery, error)
	ResolveFileHash(ctx context.Context, in *ReqResolveFileHash, opts ...grpc.CallOption) (*RespResolveFileHash, error)
	InitMultipart(ctx context.Context, in *InitReq, opts ...grpc.CallOption) (*InitResp, error)
	UploadPart(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadPartReq, UploadPartResp], error)
	CompleteMultipart(ctx context.Context, in *CompleteReq, opts ...grpc.CallOption) (*CompleteResp, error)
	AbortMultipart(ctx context.Context, in *AbortReq, opts ...grpc.CallOption) (*AbortResp, error)
	Status(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*StatusResp, error)
	DeleteFile(ctx context.Context, in *ReqDeleteFile, opts ...grpc.CallOption) (*Resp, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) Filedowm(ctx context.Context, in *ReqFileDown, opts ...grpc.CallOption) (*Resp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Resp)
	err := c.cc.Invoke(ctx, FileService_Filedowm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) LoadFile(ctx context.Context, in *Reqloadfile, opts ...grpc.CallOption) (*Resp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Resp)
	err := c.cc.Invoke(ctx, FileService_LoadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) Showfile(ctx context.Context, in *Reqshowfile, opts ...grpc.CallOption) (*Resp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Resp)
	err := c.cc.Invoke(ctx, FileService_Showfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) Filequeryinfo(ctx context.Context, in *ReqFileQuery, opts ...grpc.CallOption) (*RespFileQuery, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespFileQuery)
	err := c.cc.Invoke(ctx, FileService_Filequeryinfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ResolveFileHash(ctx context.Context, in *ReqResolveFileHash, opts ...grpc.CallOption) (*RespResolveFileHash, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespResolveFileHash)
	err := c.cc.Invoke(ctx, FileService_ResolveFileHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) InitMultipart(ctx context.Context, in *InitReq, opts ...grpc.CallOption) (*InitResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResp)
	err := c.cc.Invoke(ctx, FileService_InitMultipart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) UploadPart(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadPartReq, UploadPartResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileService_ServiceDesc.Streams[0], FileService_UploadPart_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadPartReq, UploadPartResp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileService_UploadPartClient = grpc.ClientStreamingClient[UploadPartReq, UploadPartResp]

func (c *fileServiceClient) CompleteMultipart(ctx context.Context, in *CompleteReq, opts ...grpc.CallOption) (*CompleteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteResp)
	err := c.cc.Invoke(ctx, FileService_CompleteMultipart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) AbortMultipart(ctx context.Context, in *AbortReq, opts ...grpc.CallOption) (*AbortResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortResp)
	err := c.cc.Invoke(ctx, FileService_AbortMultipart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) Status(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*StatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, FileService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DeleteFile(ctx context.Context, in *ReqDeleteFile, opts ...grpc.CallOption) (*Resp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Resp)
	err := c.cc.Invoke(ctx, FileService_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility.
type FileServiceServer interface {
	Filedowm(context.Context, *ReqFileDown) (*Resp, error)
	LoadFile(context.Context, *Reqloadfile) (*Resp, error)
	Showfile(context.Context, *Reqshowfile) (*Resp, error)
	Filequeryinfo(context.Context, *ReqFileQuery) (*RespFileQuery, error)
	ResolveFileHash(context.Context, *ReqResolveFileHash) (*RespResolveFileHash, error)
	InitMultipart(context.Context, *InitReq) (*InitResp, error)
	UploadPart(grpc.ClientStreamingServer[UploadPartReq, UploadPartResp]) error
	CompleteMultipart(context.Context, *CompleteReq) (*CompleteResp, error)
	AbortMultipart(context.Context, *AbortReq) (*AbortResp, error)
	Status(context.Context, *StatusReq) (*StatusResp, error)
	DeleteFile(context.Context, *ReqDeleteFile) (*Resp, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServiceServer struct{}

func (UnimplementedFileServiceServer) Filedowm(context.Context, *ReqFileDown) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Filedowm not implemented")
}
func (UnimplementedFileServiceServer) LoadFile(context.Context, *Reqloadfile) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadFile not implemented")
}
func (UnimplementedFileServiceServer) Showfile(context.Context, *Reqshowfile) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Showfile not implemented")
}
func (UnimplementedFileServiceServer) Filequeryinfo(context.Context, *ReqFileQuery) (*RespFileQuery, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Filequeryinfo not implemented")
}
func (UnimplementedFileServiceServer) ResolveFileHash(context.Context, *ReqResolveFileHash) (*RespResolveFileHash, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveFileHash not implemented")
}
func (UnimplementedFileServiceServer) InitMultipart(context.Context, *InitReq) (*InitResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitMultipart not implemented")
}
func (UnimplementedFileServiceServer) UploadPart(grpc.ClientStreamingServer[UploadPartReq, UploadPartResp]) error {
	return status.Errorf(codes.Unimplemented, "method UploadPart not implemented")
}
func (UnimplementedFileServiceServer) CompleteMultipart(context.Context, *CompleteReq) (*CompleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteMultipart not implemented")
}
func (UnimplementedFileServiceServer) AbortMultipart(context.Context, *AbortReq) (*AbortResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortMultipart not implemented")
}
func (UnimplementedFileServiceServer) Status(context.Context, *StatusReq) (*StatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedFileServiceServer) DeleteFile(context.Context, *ReqDeleteFile) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}
func (UnimplementedFileServiceServer) testEmbeddedByValue()                     {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_Filedowm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqFileDown)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).Filedowm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_Filedowm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).Filedowm(ctx, req.(*ReqFileDown))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_LoadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reqloadfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).LoadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_LoadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).LoadFile(ctx, req.(*Reqloadfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_Showfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reqshowfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).Showfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_Showfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).Showfile(ctx, req.(*Reqshowfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_Filequeryinfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqFileQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).Filequeryinfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_Filequeryinfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).Filequeryinfo(ctx, req.(*ReqFileQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ResolveFileHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqResolveFileHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ResolveFileHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ResolveFileHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ResolveFileHash(ctx, req.(*ReqResolveFileHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_InitMultipart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).InitMultipart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_InitMultipart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).InitMultipart(ctx, req.(*InitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_UploadPart_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileServiceServer).UploadPart(&grpc.GenericServerStream[UploadPartReq, UploadPartResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileService_UploadPartServer = grpc.ClientStreamingServer[UploadPartReq, UploadPartResp]

func _FileService_CompleteMultipart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CompleteMultipart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_CompleteMultipart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CompleteMultipart(ctx, req.(*CompleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_AbortMultipart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).AbortMultipart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_AbortMultipart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).AbortMultipart(ctx, req.(*AbortReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).Status(ctx, req.(*StatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqDeleteFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DeleteFile(ctx, req.(*ReqDeleteFile))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "file.fileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "filedowm",
			Handler:    _FileService_Filedowm_Handler,
		},
		{
			MethodName: "LoadFile",
			Handler:    _FileService_LoadFile_Handler,
		},
		{
			MethodName: "Showfile",
			Handler:    _FileService_Showfile_Handler,
		},
		{
			MethodName: "filequeryinfo",
			Handler:    _FileService_Filequeryinfo_Handler,
		},
		{
			MethodName: "ResolveFileHash",
			Handler:    _FileService_ResolveFileHash_Handler,
		},
		{
			MethodName: "InitMultipart",
			Handler:    _FileService_InitMultipart_Handler,
		},
		{
			MethodName: "CompleteMultipart",
			Handler:    _FileService_CompleteMultipart_Handler,
		},
		{
			MethodName: "AbortMultipart",
			Handler:    _FileService_AbortMultipart_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _FileService_Status_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _FileService_DeleteFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadPart",
			Handler:       _FileService_UploadPart_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "file.proto",
}
