CREATE TABLE IF NOT EXISTS `upload_sessions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `upload_id` varchar(64) NOT NULL,
  `owner_account_id` bigint unsigned NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `file_hash` varchar(64) NOT NULL,
  `file_size` bigint NOT NULL,
  `content_type` varchar(255) DEFAULT '',
  `object_key` varchar(512) NOT NULL,
  `storage_upload_id` varchar(255) NOT NULL,
  `part_size` bigint NOT NULL,
  `total_parts` bigint NOT NULL,
  `status` varchar(32) NOT NULL,
  `idempotency_key` varchar(128) DEFAULT '',
  `expires_at` datetime(3) NOT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  `last_error` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_upload_id` (`upload_id`),
  KEY `idx_upload_owner` (`owner_account_id`),
  KEY `idx_upload_hash` (`file_hash`),
  KEY `idx_upload_object` (`object_key`),
  KEY `idx_upload_status` (`status`),
  KEY `idx_upload_idempotency` (`idempotency_key`),
  KEY `idx_upload_expires` (`expires_at`),
  KEY `idx_upload_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
