LocalSocket /home/lihaoqian/project/clouddisk_v2/run/clamav/clamd-local.ctl
FixStaleSocket true
LocalSocketMode 666
PidFile /home/lihaoqian/project/clouddisk_v2/run/clamav/clamd-local.pid
LogFile /home/lihaoqian/project/clouddisk_v2/log/clamd_local.log
LogTime true
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp
ReadTimeout 180
CommandReadTimeout 120
SendBufTimeout 500
MaxThreads 4
MaxConnectionQueueLength 8
MaxQueue 32
MaxScanTime 300000
MaxScanSize 1024M
MaxFileSize 1024M
PCREMaxFileSize 1024M
StreamMaxLength 1024M
ExtendedDetectionInfo true
