// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ai.proto
#ifndef GRPC_ai_2eproto__INCLUDED
#define GRPC_ai_2eproto__INCLUDED

#include "ai.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace AI {

// AIService provides AI-related file processing capabilities.
class AIService final {
 public:
  static constexpr char const* service_full_name() {
    return "AI.AIService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // AIrequest processes an AI request for a file.
    virtual ::grpc::Status AIrequest(::grpc::ClientContext* context, const ::AI::AIReq& request, ::AI::AIResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AI::AIResp>> AsyncAIrequest(::grpc::ClientContext* context, const ::AI::AIReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AI::AIResp>>(AsyncAIrequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AI::AIResp>> PrepareAsyncAIrequest(::grpc::ClientContext* context, const ::AI::AIReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AI::AIResp>>(PrepareAsyncAIrequestRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // AIrequest processes an AI request for a file.
      virtual void AIrequest(::grpc::ClientContext* context, const ::AI::AIReq* request, ::AI::AIResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AIrequest(::grpc::ClientContext* context, const ::AI::AIReq* request, ::AI::AIResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AI::AIResp>* AsyncAIrequestRaw(::grpc::ClientContext* context, const ::AI::AIReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AI::AIResp>* PrepareAsyncAIrequestRaw(::grpc::ClientContext* context, const ::AI::AIReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AIrequest(::grpc::ClientContext* context, const ::AI::AIReq& request, ::AI::AIResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AI::AIResp>> AsyncAIrequest(::grpc::ClientContext* context, const ::AI::AIReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AI::AIResp>>(AsyncAIrequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AI::AIResp>> PrepareAsyncAIrequest(::grpc::ClientContext* context, const ::AI::AIReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AI::AIResp>>(PrepareAsyncAIrequestRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AIrequest(::grpc::ClientContext* context, const ::AI::AIReq* request, ::AI::AIResp* response, std::function<void(::grpc::Status)>) override;
      void AIrequest(::grpc::ClientContext* context, const ::AI::AIReq* request, ::AI::AIResp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::AI::AIResp>* AsyncAIrequestRaw(::grpc::ClientContext* context, const ::AI::AIReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::AI::AIResp>* PrepareAsyncAIrequestRaw(::grpc::ClientContext* context, const ::AI::AIReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AIrequest_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // AIrequest processes an AI request for a file.
    virtual ::grpc::Status AIrequest(::grpc::ServerContext* context, const ::AI::AIReq* request, ::AI::AIResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AIrequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AIrequest() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AIrequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AIrequest(::grpc::ServerContext* /*context*/, const ::AI::AIReq* /*request*/, ::AI::AIResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAIrequest(::grpc::ServerContext* context, ::AI::AIReq* request, ::grpc::ServerAsyncResponseWriter< ::AI::AIResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AIrequest<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AIrequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AIrequest() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::AI::AIReq, ::AI::AIResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::AI::AIReq* request, ::AI::AIResp* response) { return this->AIrequest(context, request, response); }));}
    void SetMessageAllocatorFor_AIrequest(
        ::grpc::MessageAllocator< ::AI::AIReq, ::AI::AIResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::AI::AIReq, ::AI::AIResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AIrequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AIrequest(::grpc::ServerContext* /*context*/, const ::AI::AIReq* /*request*/, ::AI::AIResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AIrequest(
      ::grpc::CallbackServerContext* /*context*/, const ::AI::AIReq* /*request*/, ::AI::AIResp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AIrequest<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AIrequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AIrequest() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AIrequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AIrequest(::grpc::ServerContext* /*context*/, const ::AI::AIReq* /*request*/, ::AI::AIResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AIrequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AIrequest() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AIrequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AIrequest(::grpc::ServerContext* /*context*/, const ::AI::AIReq* /*request*/, ::AI::AIResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAIrequest(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AIrequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AIrequest() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AIrequest(context, request, response); }));
    }
    ~WithRawCallbackMethod_AIrequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AIrequest(::grpc::ServerContext* /*context*/, const ::AI::AIReq* /*request*/, ::AI::AIResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AIrequest(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AIrequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AIrequest() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::AI::AIReq, ::AI::AIResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::AI::AIReq, ::AI::AIResp>* streamer) {
                       return this->StreamedAIrequest(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AIrequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AIrequest(::grpc::ServerContext* /*context*/, const ::AI::AIReq* /*request*/, ::AI::AIResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAIrequest(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::AI::AIReq,::AI::AIResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AIrequest<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AIrequest<Service > StreamedService;
};

}  // namespace AI


#endif  // GRPC_ai_2eproto__INCLUDED
