// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai.proto
// Protobuf C++ Version: 5.27.2

#include "ai.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace AI {

inline constexpr AIResp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        code_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AIResp::AIResp(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AIRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AIRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AIRespDefaultTypeInternal() {}
  union {
    AIResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AIRespDefaultTypeInternal _AIResp_default_instance_;

inline constexpr AIReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : username_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        userid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        filehash_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        query_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        file_size_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AIReq::AIReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AIReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AIReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AIReqDefaultTypeInternal() {}
  union {
    AIReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AIReqDefaultTypeInternal _AIReq_default_instance_;
}  // namespace AI
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ai_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ai_2eproto = nullptr;
const ::uint32_t
    TableStruct_ai_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::AI::AIReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AI::AIReq, _impl_.username_),
        PROTOBUF_FIELD_OFFSET(::AI::AIReq, _impl_.userid_),
        PROTOBUF_FIELD_OFFSET(::AI::AIReq, _impl_.filename_),
        PROTOBUF_FIELD_OFFSET(::AI::AIReq, _impl_.filehash_),
        PROTOBUF_FIELD_OFFSET(::AI::AIReq, _impl_.file_size_),
        PROTOBUF_FIELD_OFFSET(::AI::AIReq, _impl_.query_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::AI::AIResp, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AI::AIResp, _impl_.code_),
        PROTOBUF_FIELD_OFFSET(::AI::AIResp, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::AI::AIResp, _impl_.data_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::AI::AIReq)},
        {14, -1, -1, sizeof(::AI::AIResp)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::AI::_AIReq_default_instance_._instance,
    &::AI::_AIResp_default_instance_._instance,
};
const char descriptor_table_protodef_ai_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\010ai.proto\022\002AI\"o\n\005AIReq\022\020\n\010username\030\001 \001("
    "\t\022\016\n\006userid\030\002 \001(\t\022\020\n\010filename\030\003 \001(\t\022\020\n\010f"
    "ilehash\030\004 \001(\t\022\021\n\tfile_size\030\005 \001(\005\022\r\n\005quer"
    "y\030\006 \001(\t\"5\n\006AIResp\022\014\n\004code\030\001 \001(\005\022\017\n\007messa"
    "ge\030\002 \001(\t\022\014\n\004data\030\003 \001(\t21\n\tAIService\022$\n\tA"
    "Irequest\022\t.AI.AIReq\032\n.AI.AIResp\"\000B%Z#clo"
    "uddisk_v2/file_srv/protobuf;aipbb\006proto3"
};
static ::absl::once_flag descriptor_table_ai_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ai_2eproto = {
    false,
    false,
    280,
    descriptor_table_protodef_ai_2eproto,
    "ai.proto",
    &descriptor_table_ai_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_ai_2eproto::offsets,
    file_level_enum_descriptors_ai_2eproto,
    file_level_service_descriptors_ai_2eproto,
};
namespace AI {
// ===================================================================

class AIReq::_Internal {
 public:
};

AIReq::AIReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AI.AIReq)
}
inline PROTOBUF_NDEBUG_INLINE AIReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::AI::AIReq& from_msg)
      : username_(arena, from.username_),
        userid_(arena, from.userid_),
        filename_(arena, from.filename_),
        filehash_(arena, from.filehash_),
        query_(arena, from.query_),
        _cached_size_{0} {}

AIReq::AIReq(
    ::google::protobuf::Arena* arena,
    const AIReq& from)
    : ::google::protobuf::Message(arena) {
  AIReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.file_size_ = from._impl_.file_size_;

  // @@protoc_insertion_point(copy_constructor:AI.AIReq)
}
inline PROTOBUF_NDEBUG_INLINE AIReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : username_(arena),
        userid_(arena),
        filename_(arena),
        filehash_(arena),
        query_(arena),
        _cached_size_{0} {}

inline void AIReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.file_size_ = {};
}
AIReq::~AIReq() {
  // @@protoc_insertion_point(destructor:AI.AIReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AIReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.username_.Destroy();
  _impl_.userid_.Destroy();
  _impl_.filename_.Destroy();
  _impl_.filehash_.Destroy();
  _impl_.query_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AIReq::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(AIReq, _impl_._cached_size_),
              false,
          },
          &AIReq::MergeImpl,
          &AIReq::kDescriptorMethods,
          &descriptor_table_ai_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 52, 2> AIReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AIReq_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AI::AIReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string username = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(AIReq, _impl_.username_)}},
    // string userid = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(AIReq, _impl_.userid_)}},
    // string filename = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(AIReq, _impl_.filename_)}},
    // string filehash = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(AIReq, _impl_.filehash_)}},
    // int32 file_size = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AIReq, _impl_.file_size_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(AIReq, _impl_.file_size_)}},
    // string query = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(AIReq, _impl_.query_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string username = 1;
    {PROTOBUF_FIELD_OFFSET(AIReq, _impl_.username_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string userid = 2;
    {PROTOBUF_FIELD_OFFSET(AIReq, _impl_.userid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string filename = 3;
    {PROTOBUF_FIELD_OFFSET(AIReq, _impl_.filename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string filehash = 4;
    {PROTOBUF_FIELD_OFFSET(AIReq, _impl_.filehash_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 file_size = 5;
    {PROTOBUF_FIELD_OFFSET(AIReq, _impl_.file_size_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string query = 6;
    {PROTOBUF_FIELD_OFFSET(AIReq, _impl_.query_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\10\10\6\10\10\0\5\0"
    "AI.AIReq"
    "username"
    "userid"
    "filename"
    "filehash"
    "query"
  }},
};

PROTOBUF_NOINLINE void AIReq::Clear() {
// @@protoc_insertion_point(message_clear_start:AI.AIReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.username_.ClearToEmpty();
  _impl_.userid_.ClearToEmpty();
  _impl_.filename_.ClearToEmpty();
  _impl_.filehash_.ClearToEmpty();
  _impl_.query_.ClearToEmpty();
  _impl_.file_size_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* AIReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:AI.AIReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string username = 1;
  if (!this->_internal_username().empty()) {
    const std::string& _s = this->_internal_username();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "AI.AIReq.username");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string userid = 2;
  if (!this->_internal_userid().empty()) {
    const std::string& _s = this->_internal_userid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "AI.AIReq.userid");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string filename = 3;
  if (!this->_internal_filename().empty()) {
    const std::string& _s = this->_internal_filename();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "AI.AIReq.filename");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string filehash = 4;
  if (!this->_internal_filehash().empty()) {
    const std::string& _s = this->_internal_filehash();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "AI.AIReq.filehash");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // int32 file_size = 5;
  if (this->_internal_file_size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<5>(
            stream, this->_internal_file_size(), target);
  }

  // string query = 6;
  if (!this->_internal_query().empty()) {
    const std::string& _s = this->_internal_query();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "AI.AIReq.query");
    target = stream->WriteStringMaybeAliased(6, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AI.AIReq)
  return target;
}

::size_t AIReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AI.AIReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string username = 1;
  if (!this->_internal_username().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_username());
  }

  // string userid = 2;
  if (!this->_internal_userid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_userid());
  }

  // string filename = 3;
  if (!this->_internal_filename().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_filename());
  }

  // string filehash = 4;
  if (!this->_internal_filehash().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_filehash());
  }

  // string query = 6;
  if (!this->_internal_query().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_query());
  }

  // int32 file_size = 5;
  if (this->_internal_file_size() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_file_size());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AIReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AIReq*>(&to_msg);
  auto& from = static_cast<const AIReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AI.AIReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_username().empty()) {
    _this->_internal_set_username(from._internal_username());
  }
  if (!from._internal_userid().empty()) {
    _this->_internal_set_userid(from._internal_userid());
  }
  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (!from._internal_filehash().empty()) {
    _this->_internal_set_filehash(from._internal_filehash());
  }
  if (!from._internal_query().empty()) {
    _this->_internal_set_query(from._internal_query());
  }
  if (from._internal_file_size() != 0) {
    _this->_impl_.file_size_ = from._impl_.file_size_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AIReq::CopyFrom(const AIReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AI.AIReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AIReq::InternalSwap(AIReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.username_, &other->_impl_.username_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.userid_, &other->_impl_.userid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filehash_, &other->_impl_.filehash_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.query_, &other->_impl_.query_, arena);
        swap(_impl_.file_size_, other->_impl_.file_size_);
}

::google::protobuf::Metadata AIReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AIResp::_Internal {
 public:
};

AIResp::AIResp(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AI.AIResp)
}
inline PROTOBUF_NDEBUG_INLINE AIResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::AI::AIResp& from_msg)
      : message_(arena, from.message_),
        data_(arena, from.data_),
        _cached_size_{0} {}

AIResp::AIResp(
    ::google::protobuf::Arena* arena,
    const AIResp& from)
    : ::google::protobuf::Message(arena) {
  AIResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.code_ = from._impl_.code_;

  // @@protoc_insertion_point(copy_constructor:AI.AIResp)
}
inline PROTOBUF_NDEBUG_INLINE AIResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        data_(arena),
        _cached_size_{0} {}

inline void AIResp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.code_ = {};
}
AIResp::~AIResp() {
  // @@protoc_insertion_point(destructor:AI.AIResp)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AIResp::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.data_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AIResp::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(AIResp, _impl_._cached_size_),
              false,
          },
          &AIResp::MergeImpl,
          &AIResp::kDescriptorMethods,
          &descriptor_table_ai_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 29, 2> AIResp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AIResp_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AI::AIResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AIResp, _impl_.code_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(AIResp, _impl_.code_)}},
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(AIResp, _impl_.message_)}},
    // string data = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(AIResp, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 code = 1;
    {PROTOBUF_FIELD_OFFSET(AIResp, _impl_.code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(AIResp, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string data = 3;
    {PROTOBUF_FIELD_OFFSET(AIResp, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\11\0\7\4\0\0\0\0"
    "AI.AIResp"
    "message"
    "data"
  }},
};

PROTOBUF_NOINLINE void AIResp::Clear() {
// @@protoc_insertion_point(message_clear_start:AI.AIResp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.data_.ClearToEmpty();
  _impl_.code_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* AIResp::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:AI.AIResp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_code(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "AI.AIResp.message");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string data = 3;
  if (!this->_internal_data().empty()) {
    const std::string& _s = this->_internal_data();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "AI.AIResp.data");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AI.AIResp)
  return target;
}

::size_t AIResp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AI.AIResp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  // string data = 3;
  if (!this->_internal_data().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_data());
  }

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AIResp::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AIResp*>(&to_msg);
  auto& from = static_cast<const AIResp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AI.AIResp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_code() != 0) {
    _this->_impl_.code_ = from._impl_.code_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AIResp::CopyFrom(const AIResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AI.AIResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AIResp::InternalSwap(AIResp* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
        swap(_impl_.code_, other->_impl_.code_);
}

::google::protobuf::Metadata AIResp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace AI
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ai_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
