// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file.proto
#ifndef GRPC_file_2eproto__INCLUDED
#define GRPC_file_2eproto__INCLUDED

#include "file.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace file {

class fileService final {
 public:
  static constexpr char const* service_full_name() {
    return "file.fileService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status filedowm(::grpc::ClientContext* context, const ::file::ReqFileDown& request, ::file::Resp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>> Asyncfiledowm(::grpc::ClientContext* context, const ::file::ReqFileDown& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>>(AsyncfiledowmRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>> PrepareAsyncfiledowm(::grpc::ClientContext* context, const ::file::ReqFileDown& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>>(PrepareAsyncfiledowmRaw(context, request, cq));
    }
    virtual ::grpc::Status LoadFile(::grpc::ClientContext* context, const ::file::Reqloadfile& request, ::file::Resp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>> AsyncLoadFile(::grpc::ClientContext* context, const ::file::Reqloadfile& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>>(AsyncLoadFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>> PrepareAsyncLoadFile(::grpc::ClientContext* context, const ::file::Reqloadfile& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>>(PrepareAsyncLoadFileRaw(context, request, cq));
    }
    virtual ::grpc::Status Showfile(::grpc::ClientContext* context, const ::file::Reqshowfile& request, ::file::Resp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>> AsyncShowfile(::grpc::ClientContext* context, const ::file::Reqshowfile& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>>(AsyncShowfileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>> PrepareAsyncShowfile(::grpc::ClientContext* context, const ::file::Reqshowfile& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>>(PrepareAsyncShowfileRaw(context, request, cq));
    }
    virtual ::grpc::Status filequeryinfo(::grpc::ClientContext* context, const ::file::ReqFileQuery& request, ::file::RespFileQuery* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file::RespFileQuery>> Asyncfilequeryinfo(::grpc::ClientContext* context, const ::file::ReqFileQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file::RespFileQuery>>(AsyncfilequeryinfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file::RespFileQuery>> PrepareAsyncfilequeryinfo(::grpc::ClientContext* context, const ::file::ReqFileQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file::RespFileQuery>>(PrepareAsyncfilequeryinfoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void filedowm(::grpc::ClientContext* context, const ::file::ReqFileDown* request, ::file::Resp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void filedowm(::grpc::ClientContext* context, const ::file::ReqFileDown* request, ::file::Resp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void LoadFile(::grpc::ClientContext* context, const ::file::Reqloadfile* request, ::file::Resp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void LoadFile(::grpc::ClientContext* context, const ::file::Reqloadfile* request, ::file::Resp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Showfile(::grpc::ClientContext* context, const ::file::Reqshowfile* request, ::file::Resp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Showfile(::grpc::ClientContext* context, const ::file::Reqshowfile* request, ::file::Resp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void filequeryinfo(::grpc::ClientContext* context, const ::file::ReqFileQuery* request, ::file::RespFileQuery* response, std::function<void(::grpc::Status)>) = 0;
      virtual void filequeryinfo(::grpc::ClientContext* context, const ::file::ReqFileQuery* request, ::file::RespFileQuery* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>* AsyncfiledowmRaw(::grpc::ClientContext* context, const ::file::ReqFileDown& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>* PrepareAsyncfiledowmRaw(::grpc::ClientContext* context, const ::file::ReqFileDown& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>* AsyncLoadFileRaw(::grpc::ClientContext* context, const ::file::Reqloadfile& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>* PrepareAsyncLoadFileRaw(::grpc::ClientContext* context, const ::file::Reqloadfile& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>* AsyncShowfileRaw(::grpc::ClientContext* context, const ::file::Reqshowfile& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::file::Resp>* PrepareAsyncShowfileRaw(::grpc::ClientContext* context, const ::file::Reqshowfile& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::file::RespFileQuery>* AsyncfilequeryinfoRaw(::grpc::ClientContext* context, const ::file::ReqFileQuery& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::file::RespFileQuery>* PrepareAsyncfilequeryinfoRaw(::grpc::ClientContext* context, const ::file::ReqFileQuery& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status filedowm(::grpc::ClientContext* context, const ::file::ReqFileDown& request, ::file::Resp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file::Resp>> Asyncfiledowm(::grpc::ClientContext* context, const ::file::ReqFileDown& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file::Resp>>(AsyncfiledowmRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file::Resp>> PrepareAsyncfiledowm(::grpc::ClientContext* context, const ::file::ReqFileDown& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file::Resp>>(PrepareAsyncfiledowmRaw(context, request, cq));
    }
    ::grpc::Status LoadFile(::grpc::ClientContext* context, const ::file::Reqloadfile& request, ::file::Resp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file::Resp>> AsyncLoadFile(::grpc::ClientContext* context, const ::file::Reqloadfile& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file::Resp>>(AsyncLoadFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file::Resp>> PrepareAsyncLoadFile(::grpc::ClientContext* context, const ::file::Reqloadfile& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file::Resp>>(PrepareAsyncLoadFileRaw(context, request, cq));
    }
    ::grpc::Status Showfile(::grpc::ClientContext* context, const ::file::Reqshowfile& request, ::file::Resp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file::Resp>> AsyncShowfile(::grpc::ClientContext* context, const ::file::Reqshowfile& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file::Resp>>(AsyncShowfileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file::Resp>> PrepareAsyncShowfile(::grpc::ClientContext* context, const ::file::Reqshowfile& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file::Resp>>(PrepareAsyncShowfileRaw(context, request, cq));
    }
    ::grpc::Status filequeryinfo(::grpc::ClientContext* context, const ::file::ReqFileQuery& request, ::file::RespFileQuery* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file::RespFileQuery>> Asyncfilequeryinfo(::grpc::ClientContext* context, const ::file::ReqFileQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file::RespFileQuery>>(AsyncfilequeryinfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file::RespFileQuery>> PrepareAsyncfilequeryinfo(::grpc::ClientContext* context, const ::file::ReqFileQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file::RespFileQuery>>(PrepareAsyncfilequeryinfoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void filedowm(::grpc::ClientContext* context, const ::file::ReqFileDown* request, ::file::Resp* response, std::function<void(::grpc::Status)>) override;
      void filedowm(::grpc::ClientContext* context, const ::file::ReqFileDown* request, ::file::Resp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void LoadFile(::grpc::ClientContext* context, const ::file::Reqloadfile* request, ::file::Resp* response, std::function<void(::grpc::Status)>) override;
      void LoadFile(::grpc::ClientContext* context, const ::file::Reqloadfile* request, ::file::Resp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Showfile(::grpc::ClientContext* context, const ::file::Reqshowfile* request, ::file::Resp* response, std::function<void(::grpc::Status)>) override;
      void Showfile(::grpc::ClientContext* context, const ::file::Reqshowfile* request, ::file::Resp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void filequeryinfo(::grpc::ClientContext* context, const ::file::ReqFileQuery* request, ::file::RespFileQuery* response, std::function<void(::grpc::Status)>) override;
      void filequeryinfo(::grpc::ClientContext* context, const ::file::ReqFileQuery* request, ::file::RespFileQuery* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::file::Resp>* AsyncfiledowmRaw(::grpc::ClientContext* context, const ::file::ReqFileDown& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::file::Resp>* PrepareAsyncfiledowmRaw(::grpc::ClientContext* context, const ::file::ReqFileDown& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::file::Resp>* AsyncLoadFileRaw(::grpc::ClientContext* context, const ::file::Reqloadfile& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::file::Resp>* PrepareAsyncLoadFileRaw(::grpc::ClientContext* context, const ::file::Reqloadfile& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::file::Resp>* AsyncShowfileRaw(::grpc::ClientContext* context, const ::file::Reqshowfile& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::file::Resp>* PrepareAsyncShowfileRaw(::grpc::ClientContext* context, const ::file::Reqshowfile& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::file::RespFileQuery>* AsyncfilequeryinfoRaw(::grpc::ClientContext* context, const ::file::ReqFileQuery& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::file::RespFileQuery>* PrepareAsyncfilequeryinfoRaw(::grpc::ClientContext* context, const ::file::ReqFileQuery& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_filedowm_;
    const ::grpc::internal::RpcMethod rpcmethod_LoadFile_;
    const ::grpc::internal::RpcMethod rpcmethod_Showfile_;
    const ::grpc::internal::RpcMethod rpcmethod_filequeryinfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status filedowm(::grpc::ServerContext* context, const ::file::ReqFileDown* request, ::file::Resp* response);
    virtual ::grpc::Status LoadFile(::grpc::ServerContext* context, const ::file::Reqloadfile* request, ::file::Resp* response);
    virtual ::grpc::Status Showfile(::grpc::ServerContext* context, const ::file::Reqshowfile* request, ::file::Resp* response);
    virtual ::grpc::Status filequeryinfo(::grpc::ServerContext* context, const ::file::ReqFileQuery* request, ::file::RespFileQuery* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_filedowm : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_filedowm() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_filedowm() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status filedowm(::grpc::ServerContext* /*context*/, const ::file::ReqFileDown* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestfiledowm(::grpc::ServerContext* context, ::file::ReqFileDown* request, ::grpc::ServerAsyncResponseWriter< ::file::Resp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_LoadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_LoadFile() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_LoadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LoadFile(::grpc::ServerContext* /*context*/, const ::file::Reqloadfile* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLoadFile(::grpc::ServerContext* context, ::file::Reqloadfile* request, ::grpc::ServerAsyncResponseWriter< ::file::Resp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Showfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Showfile() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Showfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Showfile(::grpc::ServerContext* /*context*/, const ::file::Reqshowfile* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestShowfile(::grpc::ServerContext* context, ::file::Reqshowfile* request, ::grpc::ServerAsyncResponseWriter< ::file::Resp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_filequeryinfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_filequeryinfo() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_filequeryinfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status filequeryinfo(::grpc::ServerContext* /*context*/, const ::file::ReqFileQuery* /*request*/, ::file::RespFileQuery* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestfilequeryinfo(::grpc::ServerContext* context, ::file::ReqFileQuery* request, ::grpc::ServerAsyncResponseWriter< ::file::RespFileQuery>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_filedowm<WithAsyncMethod_LoadFile<WithAsyncMethod_Showfile<WithAsyncMethod_filequeryinfo<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_filedowm : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_filedowm() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::file::ReqFileDown, ::file::Resp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::file::ReqFileDown* request, ::file::Resp* response) { return this->filedowm(context, request, response); }));}
    void SetMessageAllocatorFor_filedowm(
        ::grpc::MessageAllocator< ::file::ReqFileDown, ::file::Resp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::file::ReqFileDown, ::file::Resp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_filedowm() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status filedowm(::grpc::ServerContext* /*context*/, const ::file::ReqFileDown* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* filedowm(
      ::grpc::CallbackServerContext* /*context*/, const ::file::ReqFileDown* /*request*/, ::file::Resp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_LoadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_LoadFile() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::file::Reqloadfile, ::file::Resp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::file::Reqloadfile* request, ::file::Resp* response) { return this->LoadFile(context, request, response); }));}
    void SetMessageAllocatorFor_LoadFile(
        ::grpc::MessageAllocator< ::file::Reqloadfile, ::file::Resp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::file::Reqloadfile, ::file::Resp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_LoadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LoadFile(::grpc::ServerContext* /*context*/, const ::file::Reqloadfile* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* LoadFile(
      ::grpc::CallbackServerContext* /*context*/, const ::file::Reqloadfile* /*request*/, ::file::Resp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Showfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Showfile() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::file::Reqshowfile, ::file::Resp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::file::Reqshowfile* request, ::file::Resp* response) { return this->Showfile(context, request, response); }));}
    void SetMessageAllocatorFor_Showfile(
        ::grpc::MessageAllocator< ::file::Reqshowfile, ::file::Resp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::file::Reqshowfile, ::file::Resp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Showfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Showfile(::grpc::ServerContext* /*context*/, const ::file::Reqshowfile* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Showfile(
      ::grpc::CallbackServerContext* /*context*/, const ::file::Reqshowfile* /*request*/, ::file::Resp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_filequeryinfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_filequeryinfo() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::file::ReqFileQuery, ::file::RespFileQuery>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::file::ReqFileQuery* request, ::file::RespFileQuery* response) { return this->filequeryinfo(context, request, response); }));}
    void SetMessageAllocatorFor_filequeryinfo(
        ::grpc::MessageAllocator< ::file::ReqFileQuery, ::file::RespFileQuery>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::file::ReqFileQuery, ::file::RespFileQuery>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_filequeryinfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status filequeryinfo(::grpc::ServerContext* /*context*/, const ::file::ReqFileQuery* /*request*/, ::file::RespFileQuery* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* filequeryinfo(
      ::grpc::CallbackServerContext* /*context*/, const ::file::ReqFileQuery* /*request*/, ::file::RespFileQuery* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_filedowm<WithCallbackMethod_LoadFile<WithCallbackMethod_Showfile<WithCallbackMethod_filequeryinfo<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_filedowm : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_filedowm() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_filedowm() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status filedowm(::grpc::ServerContext* /*context*/, const ::file::ReqFileDown* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_LoadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_LoadFile() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_LoadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LoadFile(::grpc::ServerContext* /*context*/, const ::file::Reqloadfile* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Showfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Showfile() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Showfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Showfile(::grpc::ServerContext* /*context*/, const ::file::Reqshowfile* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_filequeryinfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_filequeryinfo() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_filequeryinfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status filequeryinfo(::grpc::ServerContext* /*context*/, const ::file::ReqFileQuery* /*request*/, ::file::RespFileQuery* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_filedowm : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_filedowm() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_filedowm() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status filedowm(::grpc::ServerContext* /*context*/, const ::file::ReqFileDown* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestfiledowm(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_LoadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_LoadFile() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_LoadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LoadFile(::grpc::ServerContext* /*context*/, const ::file::Reqloadfile* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLoadFile(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Showfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Showfile() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_Showfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Showfile(::grpc::ServerContext* /*context*/, const ::file::Reqshowfile* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestShowfile(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_filequeryinfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_filequeryinfo() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_filequeryinfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status filequeryinfo(::grpc::ServerContext* /*context*/, const ::file::ReqFileQuery* /*request*/, ::file::RespFileQuery* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestfilequeryinfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_filedowm : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_filedowm() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->filedowm(context, request, response); }));
    }
    ~WithRawCallbackMethod_filedowm() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status filedowm(::grpc::ServerContext* /*context*/, const ::file::ReqFileDown* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* filedowm(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_LoadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_LoadFile() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->LoadFile(context, request, response); }));
    }
    ~WithRawCallbackMethod_LoadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LoadFile(::grpc::ServerContext* /*context*/, const ::file::Reqloadfile* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* LoadFile(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Showfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Showfile() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Showfile(context, request, response); }));
    }
    ~WithRawCallbackMethod_Showfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Showfile(::grpc::ServerContext* /*context*/, const ::file::Reqshowfile* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Showfile(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_filequeryinfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_filequeryinfo() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->filequeryinfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_filequeryinfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status filequeryinfo(::grpc::ServerContext* /*context*/, const ::file::ReqFileQuery* /*request*/, ::file::RespFileQuery* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* filequeryinfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_filedowm : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_filedowm() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::file::ReqFileDown, ::file::Resp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::file::ReqFileDown, ::file::Resp>* streamer) {
                       return this->Streamedfiledowm(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_filedowm() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status filedowm(::grpc::ServerContext* /*context*/, const ::file::ReqFileDown* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedfiledowm(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::file::ReqFileDown,::file::Resp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_LoadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_LoadFile() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::file::Reqloadfile, ::file::Resp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::file::Reqloadfile, ::file::Resp>* streamer) {
                       return this->StreamedLoadFile(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_LoadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status LoadFile(::grpc::ServerContext* /*context*/, const ::file::Reqloadfile* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLoadFile(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::file::Reqloadfile,::file::Resp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Showfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Showfile() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::file::Reqshowfile, ::file::Resp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::file::Reqshowfile, ::file::Resp>* streamer) {
                       return this->StreamedShowfile(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Showfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Showfile(::grpc::ServerContext* /*context*/, const ::file::Reqshowfile* /*request*/, ::file::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedShowfile(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::file::Reqshowfile,::file::Resp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_filequeryinfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_filequeryinfo() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::file::ReqFileQuery, ::file::RespFileQuery>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::file::ReqFileQuery, ::file::RespFileQuery>* streamer) {
                       return this->Streamedfilequeryinfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_filequeryinfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status filequeryinfo(::grpc::ServerContext* /*context*/, const ::file::ReqFileQuery* /*request*/, ::file::RespFileQuery* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedfilequeryinfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::file::ReqFileQuery,::file::RespFileQuery>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_filedowm<WithStreamedUnaryMethod_LoadFile<WithStreamedUnaryMethod_Showfile<WithStreamedUnaryMethod_filequeryinfo<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_filedowm<WithStreamedUnaryMethod_LoadFile<WithStreamedUnaryMethod_Showfile<WithStreamedUnaryMethod_filequeryinfo<Service > > > > StreamedService;
};

}  // namespace file


#endif  // GRPC_file_2eproto__INCLUDED
