// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file.proto

#include "file.pb.h"
#include "file.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace file {

static const char* fileService_method_names[] = {
  "/file.fileService/filedowm",
  "/file.fileService/LoadFile",
  "/file.fileService/Showfile",
  "/file.fileService/filequeryinfo",
  "/file.fileService/ResolveFileHash",
};

std::unique_ptr< fileService::Stub> fileService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< fileService::Stub> stub(new fileService::Stub(channel, options));
  return stub;
}

fileService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_filedowm_(fileService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LoadFile_(fileService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Showfile_(fileService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_filequeryinfo_(fileService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ResolveFileHash_(fileService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status fileService::Stub::filedowm(::grpc::ClientContext* context, const ::file::ReqFileDown& request, ::file::Resp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::file::ReqFileDown, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_filedowm_, context, request, response);
}

void fileService::Stub::async::filedowm(::grpc::ClientContext* context, const ::file::ReqFileDown* request, ::file::Resp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::file::ReqFileDown, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_filedowm_, context, request, response, std::move(f));
}

void fileService::Stub::async::filedowm(::grpc::ClientContext* context, const ::file::ReqFileDown* request, ::file::Resp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_filedowm_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::file::Resp>* fileService::Stub::PrepareAsyncfiledowmRaw(::grpc::ClientContext* context, const ::file::ReqFileDown& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::file::Resp, ::file::ReqFileDown, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_filedowm_, context, request);
}

::grpc::ClientAsyncResponseReader< ::file::Resp>* fileService::Stub::AsyncfiledowmRaw(::grpc::ClientContext* context, const ::file::ReqFileDown& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncfiledowmRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status fileService::Stub::LoadFile(::grpc::ClientContext* context, const ::file::Reqloadfile& request, ::file::Resp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::file::Reqloadfile, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LoadFile_, context, request, response);
}

void fileService::Stub::async::LoadFile(::grpc::ClientContext* context, const ::file::Reqloadfile* request, ::file::Resp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::file::Reqloadfile, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LoadFile_, context, request, response, std::move(f));
}

void fileService::Stub::async::LoadFile(::grpc::ClientContext* context, const ::file::Reqloadfile* request, ::file::Resp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LoadFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::file::Resp>* fileService::Stub::PrepareAsyncLoadFileRaw(::grpc::ClientContext* context, const ::file::Reqloadfile& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::file::Resp, ::file::Reqloadfile, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LoadFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::file::Resp>* fileService::Stub::AsyncLoadFileRaw(::grpc::ClientContext* context, const ::file::Reqloadfile& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoadFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status fileService::Stub::Showfile(::grpc::ClientContext* context, const ::file::Reqshowfile& request, ::file::Resp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::file::Reqshowfile, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Showfile_, context, request, response);
}

void fileService::Stub::async::Showfile(::grpc::ClientContext* context, const ::file::Reqshowfile* request, ::file::Resp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::file::Reqshowfile, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Showfile_, context, request, response, std::move(f));
}

void fileService::Stub::async::Showfile(::grpc::ClientContext* context, const ::file::Reqshowfile* request, ::file::Resp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Showfile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::file::Resp>* fileService::Stub::PrepareAsyncShowfileRaw(::grpc::ClientContext* context, const ::file::Reqshowfile& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::file::Resp, ::file::Reqshowfile, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Showfile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::file::Resp>* fileService::Stub::AsyncShowfileRaw(::grpc::ClientContext* context, const ::file::Reqshowfile& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncShowfileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status fileService::Stub::filequeryinfo(::grpc::ClientContext* context, const ::file::ReqFileQuery& request, ::file::RespFileQuery* response) {
  return ::grpc::internal::BlockingUnaryCall< ::file::ReqFileQuery, ::file::RespFileQuery, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_filequeryinfo_, context, request, response);
}

void fileService::Stub::async::filequeryinfo(::grpc::ClientContext* context, const ::file::ReqFileQuery* request, ::file::RespFileQuery* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::file::ReqFileQuery, ::file::RespFileQuery, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_filequeryinfo_, context, request, response, std::move(f));
}

void fileService::Stub::async::filequeryinfo(::grpc::ClientContext* context, const ::file::ReqFileQuery* request, ::file::RespFileQuery* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_filequeryinfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::file::RespFileQuery>* fileService::Stub::PrepareAsyncfilequeryinfoRaw(::grpc::ClientContext* context, const ::file::ReqFileQuery& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::file::RespFileQuery, ::file::ReqFileQuery, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_filequeryinfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::file::RespFileQuery>* fileService::Stub::AsyncfilequeryinfoRaw(::grpc::ClientContext* context, const ::file::ReqFileQuery& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncfilequeryinfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status fileService::Stub::ResolveFileHash(::grpc::ClientContext* context, const ::file::ReqResolveFileHash& request, ::file::RespResolveFileHash* response) {
  return ::grpc::internal::BlockingUnaryCall< ::file::ReqResolveFileHash, ::file::RespResolveFileHash, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ResolveFileHash_, context, request, response);
}

void fileService::Stub::async::ResolveFileHash(::grpc::ClientContext* context, const ::file::ReqResolveFileHash* request, ::file::RespResolveFileHash* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::file::ReqResolveFileHash, ::file::RespResolveFileHash, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ResolveFileHash_, context, request, response, std::move(f));
}

void fileService::Stub::async::ResolveFileHash(::grpc::ClientContext* context, const ::file::ReqResolveFileHash* request, ::file::RespResolveFileHash* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ResolveFileHash_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::file::RespResolveFileHash>* fileService::Stub::PrepareAsyncResolveFileHashRaw(::grpc::ClientContext* context, const ::file::ReqResolveFileHash& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::file::RespResolveFileHash, ::file::ReqResolveFileHash, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ResolveFileHash_, context, request);
}

::grpc::ClientAsyncResponseReader< ::file::RespResolveFileHash>* fileService::Stub::AsyncResolveFileHashRaw(::grpc::ClientContext* context, const ::file::ReqResolveFileHash& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncResolveFileHashRaw(context, request, cq);
  result->StartCall();
  return result;
}

fileService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< fileService::Service, ::file::ReqFileDown, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::file::ReqFileDown* req,
             ::file::Resp* resp) {
               return service->filedowm(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< fileService::Service, ::file::Reqloadfile, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::file::Reqloadfile* req,
             ::file::Resp* resp) {
               return service->LoadFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< fileService::Service, ::file::Reqshowfile, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::file::Reqshowfile* req,
             ::file::Resp* resp) {
               return service->Showfile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< fileService::Service, ::file::ReqFileQuery, ::file::RespFileQuery, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::file::ReqFileQuery* req,
             ::file::RespFileQuery* resp) {
               return service->filequeryinfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< fileService::Service, ::file::ReqResolveFileHash, ::file::RespResolveFileHash, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::file::ReqResolveFileHash* req,
             ::file::RespResolveFileHash* resp) {
               return service->ResolveFileHash(ctx, req, resp);
             }, this)));
}

fileService::Service::~Service() {
}

::grpc::Status fileService::Service::filedowm(::grpc::ServerContext* context, const ::file::ReqFileDown* request, ::file::Resp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status fileService::Service::LoadFile(::grpc::ServerContext* context, const ::file::Reqloadfile* request, ::file::Resp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status fileService::Service::Showfile(::grpc::ServerContext* context, const ::file::Reqshowfile* request, ::file::Resp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status fileService::Service::filequeryinfo(::grpc::ServerContext* context, const ::file::ReqFileQuery* request, ::file::RespFileQuery* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status fileService::Service::ResolveFileHash(::grpc::ServerContext* context, const ::file::ReqResolveFileHash* request, ::file::RespResolveFileHash* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace file

