// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file.proto

#include "file.pb.h"
#include "file.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace file {

static const char* fileService_method_names[] = {
  "/file.fileService/filedowm",
  "/file.fileService/LoadFile",
  "/file.fileService/UploadFile",
  "/file.fileService/Showfile",
  "/file.fileService/filequeryinfo",
  "/file.fileService/ResolveFileHash",
  "/file.fileService/InitMultipart",
  "/file.fileService/PresignParts",
  "/file.fileService/UploadPart",
  "/file.fileService/CompleteMultipart",
  "/file.fileService/AbortMultipart",
  "/file.fileService/Status",
  "/file.fileService/DeleteFile",
};

std::unique_ptr< fileService::Stub> fileService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< fileService::Stub> stub(new fileService::Stub(channel, options));
  return stub;
}

fileService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_filedowm_(fileService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LoadFile_(fileService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UploadFile_(fileService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_Showfile_(fileService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_filequeryinfo_(fileService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ResolveFileHash_(fileService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_InitMultipart_(fileService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PresignParts_(fileService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UploadPart_(fileService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_CompleteMultipart_(fileService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AbortMultipart_(fileService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Status_(fileService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteFile_(fileService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status fileService::Stub::filedowm(::grpc::ClientContext* context, const ::file::ReqFileDown& request, ::file::Resp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::file::ReqFileDown, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_filedowm_, context, request, response);
}

void fileService::Stub::async::filedowm(::grpc::ClientContext* context, const ::file::ReqFileDown* request, ::file::Resp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::file::ReqFileDown, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_filedowm_, context, request, response, std::move(f));
}

void fileService::Stub::async::filedowm(::grpc::ClientContext* context, const ::file::ReqFileDown* request, ::file::Resp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_filedowm_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::file::Resp>* fileService::Stub::PrepareAsyncfiledowmRaw(::grpc::ClientContext* context, const ::file::ReqFileDown& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::file::Resp, ::file::ReqFileDown, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_filedowm_, context, request);
}

::grpc::ClientAsyncResponseReader< ::file::Resp>* fileService::Stub::AsyncfiledowmRaw(::grpc::ClientContext* context, const ::file::ReqFileDown& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncfiledowmRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status fileService::Stub::LoadFile(::grpc::ClientContext* context, const ::file::Reqloadfile& request, ::file::Resp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::file::Reqloadfile, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LoadFile_, context, request, response);
}

void fileService::Stub::async::LoadFile(::grpc::ClientContext* context, const ::file::Reqloadfile* request, ::file::Resp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::file::Reqloadfile, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LoadFile_, context, request, response, std::move(f));
}

void fileService::Stub::async::LoadFile(::grpc::ClientContext* context, const ::file::Reqloadfile* request, ::file::Resp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LoadFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::file::Resp>* fileService::Stub::PrepareAsyncLoadFileRaw(::grpc::ClientContext* context, const ::file::Reqloadfile& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::file::Resp, ::file::Reqloadfile, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LoadFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::file::Resp>* fileService::Stub::AsyncLoadFileRaw(::grpc::ClientContext* context, const ::file::Reqloadfile& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoadFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientWriter< ::file::UploadFileReq>* fileService::Stub::UploadFileRaw(::grpc::ClientContext* context, ::file::UploadFileResp* response) {
  return ::grpc::internal::ClientWriterFactory< ::file::UploadFileReq>::Create(channel_.get(), rpcmethod_UploadFile_, context, response);
}

void fileService::Stub::async::UploadFile(::grpc::ClientContext* context, ::file::UploadFileResp* response, ::grpc::ClientWriteReactor< ::file::UploadFileReq>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::file::UploadFileReq>::Create(stub_->channel_.get(), stub_->rpcmethod_UploadFile_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::file::UploadFileReq>* fileService::Stub::AsyncUploadFileRaw(::grpc::ClientContext* context, ::file::UploadFileResp* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::file::UploadFileReq>::Create(channel_.get(), cq, rpcmethod_UploadFile_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::file::UploadFileReq>* fileService::Stub::PrepareAsyncUploadFileRaw(::grpc::ClientContext* context, ::file::UploadFileResp* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::file::UploadFileReq>::Create(channel_.get(), cq, rpcmethod_UploadFile_, context, response, false, nullptr);
}

::grpc::Status fileService::Stub::Showfile(::grpc::ClientContext* context, const ::file::Reqshowfile& request, ::file::Resp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::file::Reqshowfile, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Showfile_, context, request, response);
}

void fileService::Stub::async::Showfile(::grpc::ClientContext* context, const ::file::Reqshowfile* request, ::file::Resp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::file::Reqshowfile, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Showfile_, context, request, response, std::move(f));
}

void fileService::Stub::async::Showfile(::grpc::ClientContext* context, const ::file::Reqshowfile* request, ::file::Resp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Showfile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::file::Resp>* fileService::Stub::PrepareAsyncShowfileRaw(::grpc::ClientContext* context, const ::file::Reqshowfile& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::file::Resp, ::file::Reqshowfile, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Showfile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::file::Resp>* fileService::Stub::AsyncShowfileRaw(::grpc::ClientContext* context, const ::file::Reqshowfile& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncShowfileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status fileService::Stub::filequeryinfo(::grpc::ClientContext* context, const ::file::ReqFileQuery& request, ::file::RespFileQuery* response) {
  return ::grpc::internal::BlockingUnaryCall< ::file::ReqFileQuery, ::file::RespFileQuery, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_filequeryinfo_, context, request, response);
}

void fileService::Stub::async::filequeryinfo(::grpc::ClientContext* context, const ::file::ReqFileQuery* request, ::file::RespFileQuery* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::file::ReqFileQuery, ::file::RespFileQuery, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_filequeryinfo_, context, request, response, std::move(f));
}

void fileService::Stub::async::filequeryinfo(::grpc::ClientContext* context, const ::file::ReqFileQuery* request, ::file::RespFileQuery* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_filequeryinfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::file::RespFileQuery>* fileService::Stub::PrepareAsyncfilequeryinfoRaw(::grpc::ClientContext* context, const ::file::ReqFileQuery& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::file::RespFileQuery, ::file::ReqFileQuery, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_filequeryinfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::file::RespFileQuery>* fileService::Stub::AsyncfilequeryinfoRaw(::grpc::ClientContext* context, const ::file::ReqFileQuery& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncfilequeryinfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status fileService::Stub::ResolveFileHash(::grpc::ClientContext* context, const ::file::ReqResolveFileHash& request, ::file::RespResolveFileHash* response) {
  return ::grpc::internal::BlockingUnaryCall< ::file::ReqResolveFileHash, ::file::RespResolveFileHash, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ResolveFileHash_, context, request, response);
}

void fileService::Stub::async::ResolveFileHash(::grpc::ClientContext* context, const ::file::ReqResolveFileHash* request, ::file::RespResolveFileHash* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::file::ReqResolveFileHash, ::file::RespResolveFileHash, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ResolveFileHash_, context, request, response, std::move(f));
}

void fileService::Stub::async::ResolveFileHash(::grpc::ClientContext* context, const ::file::ReqResolveFileHash* request, ::file::RespResolveFileHash* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ResolveFileHash_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::file::RespResolveFileHash>* fileService::Stub::PrepareAsyncResolveFileHashRaw(::grpc::ClientContext* context, const ::file::ReqResolveFileHash& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::file::RespResolveFileHash, ::file::ReqResolveFileHash, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ResolveFileHash_, context, request);
}

::grpc::ClientAsyncResponseReader< ::file::RespResolveFileHash>* fileService::Stub::AsyncResolveFileHashRaw(::grpc::ClientContext* context, const ::file::ReqResolveFileHash& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncResolveFileHashRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status fileService::Stub::InitMultipart(::grpc::ClientContext* context, const ::file::InitReq& request, ::file::InitResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::file::InitReq, ::file::InitResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_InitMultipart_, context, request, response);
}

void fileService::Stub::async::InitMultipart(::grpc::ClientContext* context, const ::file::InitReq* request, ::file::InitResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::file::InitReq, ::file::InitResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InitMultipart_, context, request, response, std::move(f));
}

void fileService::Stub::async::InitMultipart(::grpc::ClientContext* context, const ::file::InitReq* request, ::file::InitResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InitMultipart_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::file::InitResp>* fileService::Stub::PrepareAsyncInitMultipartRaw(::grpc::ClientContext* context, const ::file::InitReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::file::InitResp, ::file::InitReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_InitMultipart_, context, request);
}

::grpc::ClientAsyncResponseReader< ::file::InitResp>* fileService::Stub::AsyncInitMultipartRaw(::grpc::ClientContext* context, const ::file::InitReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInitMultipartRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status fileService::Stub::PresignParts(::grpc::ClientContext* context, const ::file::PresignPartsReq& request, ::file::PresignPartsResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::file::PresignPartsReq, ::file::PresignPartsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PresignParts_, context, request, response);
}

void fileService::Stub::async::PresignParts(::grpc::ClientContext* context, const ::file::PresignPartsReq* request, ::file::PresignPartsResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::file::PresignPartsReq, ::file::PresignPartsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PresignParts_, context, request, response, std::move(f));
}

void fileService::Stub::async::PresignParts(::grpc::ClientContext* context, const ::file::PresignPartsReq* request, ::file::PresignPartsResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PresignParts_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::file::PresignPartsResp>* fileService::Stub::PrepareAsyncPresignPartsRaw(::grpc::ClientContext* context, const ::file::PresignPartsReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::file::PresignPartsResp, ::file::PresignPartsReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PresignParts_, context, request);
}

::grpc::ClientAsyncResponseReader< ::file::PresignPartsResp>* fileService::Stub::AsyncPresignPartsRaw(::grpc::ClientContext* context, const ::file::PresignPartsReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPresignPartsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientWriter< ::file::UploadPartReq>* fileService::Stub::UploadPartRaw(::grpc::ClientContext* context, ::file::UploadPartResp* response) {
  return ::grpc::internal::ClientWriterFactory< ::file::UploadPartReq>::Create(channel_.get(), rpcmethod_UploadPart_, context, response);
}

void fileService::Stub::async::UploadPart(::grpc::ClientContext* context, ::file::UploadPartResp* response, ::grpc::ClientWriteReactor< ::file::UploadPartReq>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::file::UploadPartReq>::Create(stub_->channel_.get(), stub_->rpcmethod_UploadPart_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::file::UploadPartReq>* fileService::Stub::AsyncUploadPartRaw(::grpc::ClientContext* context, ::file::UploadPartResp* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::file::UploadPartReq>::Create(channel_.get(), cq, rpcmethod_UploadPart_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::file::UploadPartReq>* fileService::Stub::PrepareAsyncUploadPartRaw(::grpc::ClientContext* context, ::file::UploadPartResp* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::file::UploadPartReq>::Create(channel_.get(), cq, rpcmethod_UploadPart_, context, response, false, nullptr);
}

::grpc::Status fileService::Stub::CompleteMultipart(::grpc::ClientContext* context, const ::file::CompleteReq& request, ::file::CompleteResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::file::CompleteReq, ::file::CompleteResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CompleteMultipart_, context, request, response);
}

void fileService::Stub::async::CompleteMultipart(::grpc::ClientContext* context, const ::file::CompleteReq* request, ::file::CompleteResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::file::CompleteReq, ::file::CompleteResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CompleteMultipart_, context, request, response, std::move(f));
}

void fileService::Stub::async::CompleteMultipart(::grpc::ClientContext* context, const ::file::CompleteReq* request, ::file::CompleteResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CompleteMultipart_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::file::CompleteResp>* fileService::Stub::PrepareAsyncCompleteMultipartRaw(::grpc::ClientContext* context, const ::file::CompleteReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::file::CompleteResp, ::file::CompleteReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CompleteMultipart_, context, request);
}

::grpc::ClientAsyncResponseReader< ::file::CompleteResp>* fileService::Stub::AsyncCompleteMultipartRaw(::grpc::ClientContext* context, const ::file::CompleteReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCompleteMultipartRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status fileService::Stub::AbortMultipart(::grpc::ClientContext* context, const ::file::AbortReq& request, ::file::AbortResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::file::AbortReq, ::file::AbortResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AbortMultipart_, context, request, response);
}

void fileService::Stub::async::AbortMultipart(::grpc::ClientContext* context, const ::file::AbortReq* request, ::file::AbortResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::file::AbortReq, ::file::AbortResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AbortMultipart_, context, request, response, std::move(f));
}

void fileService::Stub::async::AbortMultipart(::grpc::ClientContext* context, const ::file::AbortReq* request, ::file::AbortResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AbortMultipart_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::file::AbortResp>* fileService::Stub::PrepareAsyncAbortMultipartRaw(::grpc::ClientContext* context, const ::file::AbortReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::file::AbortResp, ::file::AbortReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AbortMultipart_, context, request);
}

::grpc::ClientAsyncResponseReader< ::file::AbortResp>* fileService::Stub::AsyncAbortMultipartRaw(::grpc::ClientContext* context, const ::file::AbortReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAbortMultipartRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status fileService::Stub::Status(::grpc::ClientContext* context, const ::file::StatusReq& request, ::file::StatusResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::file::StatusReq, ::file::StatusResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Status_, context, request, response);
}

void fileService::Stub::async::Status(::grpc::ClientContext* context, const ::file::StatusReq* request, ::file::StatusResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::file::StatusReq, ::file::StatusResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Status_, context, request, response, std::move(f));
}

void fileService::Stub::async::Status(::grpc::ClientContext* context, const ::file::StatusReq* request, ::file::StatusResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Status_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::file::StatusResp>* fileService::Stub::PrepareAsyncStatusRaw(::grpc::ClientContext* context, const ::file::StatusReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::file::StatusResp, ::file::StatusReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Status_, context, request);
}

::grpc::ClientAsyncResponseReader< ::file::StatusResp>* fileService::Stub::AsyncStatusRaw(::grpc::ClientContext* context, const ::file::StatusReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status fileService::Stub::DeleteFile(::grpc::ClientContext* context, const ::file::ReqDeleteFile& request, ::file::Resp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::file::ReqDeleteFile, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteFile_, context, request, response);
}

void fileService::Stub::async::DeleteFile(::grpc::ClientContext* context, const ::file::ReqDeleteFile* request, ::file::Resp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::file::ReqDeleteFile, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteFile_, context, request, response, std::move(f));
}

void fileService::Stub::async::DeleteFile(::grpc::ClientContext* context, const ::file::ReqDeleteFile* request, ::file::Resp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::file::Resp>* fileService::Stub::PrepareAsyncDeleteFileRaw(::grpc::ClientContext* context, const ::file::ReqDeleteFile& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::file::Resp, ::file::ReqDeleteFile, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::file::Resp>* fileService::Stub::AsyncDeleteFileRaw(::grpc::ClientContext* context, const ::file::ReqDeleteFile& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

fileService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< fileService::Service, ::file::ReqFileDown, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::file::ReqFileDown* req,
             ::file::Resp* resp) {
               return service->filedowm(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< fileService::Service, ::file::Reqloadfile, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::file::Reqloadfile* req,
             ::file::Resp* resp) {
               return service->LoadFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[2],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< fileService::Service, ::file::UploadFileReq, ::file::UploadFileResp>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::file::UploadFileReq>* reader,
             ::file::UploadFileResp* resp) {
               return service->UploadFile(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< fileService::Service, ::file::Reqshowfile, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::file::Reqshowfile* req,
             ::file::Resp* resp) {
               return service->Showfile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< fileService::Service, ::file::ReqFileQuery, ::file::RespFileQuery, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::file::ReqFileQuery* req,
             ::file::RespFileQuery* resp) {
               return service->filequeryinfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< fileService::Service, ::file::ReqResolveFileHash, ::file::RespResolveFileHash, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::file::ReqResolveFileHash* req,
             ::file::RespResolveFileHash* resp) {
               return service->ResolveFileHash(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< fileService::Service, ::file::InitReq, ::file::InitResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::file::InitReq* req,
             ::file::InitResp* resp) {
               return service->InitMultipart(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< fileService::Service, ::file::PresignPartsReq, ::file::PresignPartsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::file::PresignPartsReq* req,
             ::file::PresignPartsResp* resp) {
               return service->PresignParts(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[8],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< fileService::Service, ::file::UploadPartReq, ::file::UploadPartResp>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::file::UploadPartReq>* reader,
             ::file::UploadPartResp* resp) {
               return service->UploadPart(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< fileService::Service, ::file::CompleteReq, ::file::CompleteResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::file::CompleteReq* req,
             ::file::CompleteResp* resp) {
               return service->CompleteMultipart(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< fileService::Service, ::file::AbortReq, ::file::AbortResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::file::AbortReq* req,
             ::file::AbortResp* resp) {
               return service->AbortMultipart(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< fileService::Service, ::file::StatusReq, ::file::StatusResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::file::StatusReq* req,
             ::file::StatusResp* resp) {
               return service->Status(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      fileService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< fileService::Service, ::file::ReqDeleteFile, ::file::Resp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](fileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::file::ReqDeleteFile* req,
             ::file::Resp* resp) {
               return service->DeleteFile(ctx, req, resp);
             }, this)));
}

fileService::Service::~Service() {
}

::grpc::Status fileService::Service::filedowm(::grpc::ServerContext* context, const ::file::ReqFileDown* request, ::file::Resp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status fileService::Service::LoadFile(::grpc::ServerContext* context, const ::file::Reqloadfile* request, ::file::Resp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status fileService::Service::UploadFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::file::UploadFileReq>* reader, ::file::UploadFileResp* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status fileService::Service::Showfile(::grpc::ServerContext* context, const ::file::Reqshowfile* request, ::file::Resp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status fileService::Service::filequeryinfo(::grpc::ServerContext* context, const ::file::ReqFileQuery* request, ::file::RespFileQuery* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status fileService::Service::ResolveFileHash(::grpc::ServerContext* context, const ::file::ReqResolveFileHash* request, ::file::RespResolveFileHash* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status fileService::Service::InitMultipart(::grpc::ServerContext* context, const ::file::InitReq* request, ::file::InitResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status fileService::Service::PresignParts(::grpc::ServerContext* context, const ::file::PresignPartsReq* request, ::file::PresignPartsResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status fileService::Service::UploadPart(::grpc::ServerContext* context, ::grpc::ServerReader< ::file::UploadPartReq>* reader, ::file::UploadPartResp* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status fileService::Service::CompleteMultipart(::grpc::ServerContext* context, const ::file::CompleteReq* request, ::file::CompleteResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status fileService::Service::AbortMultipart(::grpc::ServerContext* context, const ::file::AbortReq* request, ::file::AbortResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status fileService::Service::Status(::grpc::ServerContext* context, const ::file::StatusReq* request, ::file::StatusResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status fileService::Service::DeleteFile(::grpc::ServerContext* context, const ::file::ReqDeleteFile* request, ::file::Resp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace file

