// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.2
// source: ai.proto

package aipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AIReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Userid        string                 `protobuf:"bytes,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Filehash      string                 `protobuf:"bytes,4,opt,name=filehash,proto3" json:"filehash,omitempty"`
	FileSize      int32                  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Query         string                 `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIReq) Reset() {
	*x = AIReq{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIReq) ProtoMessage() {}

func (x *AIReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIReq.ProtoReflect.Descriptor instead.
func (*AIReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *AIReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AIReq) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *AIReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AIReq) GetFilehash() string {
	if x != nil {
		return x.Filehash
	}
	return ""
}

func (x *AIReq) GetFileSize() int32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *AIReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type AIResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIResp) Reset() {
	*x = AIResp{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIResp) ProtoMessage() {}

func (x *AIResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIResp.ProtoReflect.Descriptor instead.
func (*AIResp) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *AIResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AIResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AIResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x02AI\"\xa6\x01\n" +
	"\x05AIReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06userid\x18\x02 \x01(\tR\x06userid\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1a\n" +
	"\bfilehash\x18\x04 \x01(\tR\bfilehash\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x05R\bfileSize\x12\x14\n" +
	"\x05query\x18\x06 \x01(\tR\x05query\"J\n" +
	"\x06AIResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data21\n" +
	"\tAIService\x12$\n" +
	"\tAIrequest\x12\t.AI.AIReq\x1a\n" +
	".AI.AIResp\"\x00B#Z!clouddisk_v2/AI_srv/protobuf;aipbb\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_proto_goTypes = []any{
	(*AIReq)(nil),  // 0: AI.AIReq
	(*AIResp)(nil), // 1: AI.AIResp
}
var file_ai_proto_depIdxs = []int32{
	0, // 0: AI.AIService.AIrequest:input_type -> AI.AIReq
	1, // 1: AI.AIService.AIrequest:output_type -> AI.AIResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
