// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: account.proto
#ifndef GRPC_account_2eproto__INCLUDED
#define GRPC_account_2eproto__INCLUDED

#include "account.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace account {

class accountService final {
 public:
  static constexpr char const* service_full_name() {
    return "account.accountService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Signin(::grpc::ClientContext* context, const ::account::ReqSignin& request, ::account::Resp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>> AsyncSignin(::grpc::ClientContext* context, const ::account::ReqSignin& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>>(AsyncSigninRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>> PrepareAsyncSignin(::grpc::ClientContext* context, const ::account::ReqSignin& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>>(PrepareAsyncSigninRaw(context, request, cq));
    }
    virtual ::grpc::Status Signup(::grpc::ClientContext* context, const ::account::ReqSignup& request, ::account::Resp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>> AsyncSignup(::grpc::ClientContext* context, const ::account::ReqSignup& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>>(AsyncSignupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>> PrepareAsyncSignup(::grpc::ClientContext* context, const ::account::ReqSignup& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>>(PrepareAsyncSignupRaw(context, request, cq));
    }
    virtual ::grpc::Status VerifyCode(::grpc::ClientContext* context, const ::account::Reqverifycode& request, ::account::Resp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>> AsyncVerifyCode(::grpc::ClientContext* context, const ::account::Reqverifycode& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>>(AsyncVerifyCodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>> PrepareAsyncVerifyCode(::grpc::ClientContext* context, const ::account::Reqverifycode& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>>(PrepareAsyncVerifyCodeRaw(context, request, cq));
    }
    virtual ::grpc::Status Userinfo(::grpc::ClientContext* context, const ::account::ReqUserinfo& request, ::account::Resp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>> AsyncUserinfo(::grpc::ClientContext* context, const ::account::ReqUserinfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>>(AsyncUserinfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>> PrepareAsyncUserinfo(::grpc::ClientContext* context, const ::account::ReqUserinfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>>(PrepareAsyncUserinfoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Signin(::grpc::ClientContext* context, const ::account::ReqSignin* request, ::account::Resp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Signin(::grpc::ClientContext* context, const ::account::ReqSignin* request, ::account::Resp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Signup(::grpc::ClientContext* context, const ::account::ReqSignup* request, ::account::Resp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Signup(::grpc::ClientContext* context, const ::account::ReqSignup* request, ::account::Resp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void VerifyCode(::grpc::ClientContext* context, const ::account::Reqverifycode* request, ::account::Resp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void VerifyCode(::grpc::ClientContext* context, const ::account::Reqverifycode* request, ::account::Resp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Userinfo(::grpc::ClientContext* context, const ::account::ReqUserinfo* request, ::account::Resp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Userinfo(::grpc::ClientContext* context, const ::account::ReqUserinfo* request, ::account::Resp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>* AsyncSigninRaw(::grpc::ClientContext* context, const ::account::ReqSignin& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>* PrepareAsyncSigninRaw(::grpc::ClientContext* context, const ::account::ReqSignin& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>* AsyncSignupRaw(::grpc::ClientContext* context, const ::account::ReqSignup& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>* PrepareAsyncSignupRaw(::grpc::ClientContext* context, const ::account::ReqSignup& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>* AsyncVerifyCodeRaw(::grpc::ClientContext* context, const ::account::Reqverifycode& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>* PrepareAsyncVerifyCodeRaw(::grpc::ClientContext* context, const ::account::Reqverifycode& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>* AsyncUserinfoRaw(::grpc::ClientContext* context, const ::account::ReqUserinfo& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::Resp>* PrepareAsyncUserinfoRaw(::grpc::ClientContext* context, const ::account::ReqUserinfo& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Signin(::grpc::ClientContext* context, const ::account::ReqSignin& request, ::account::Resp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::Resp>> AsyncSignin(::grpc::ClientContext* context, const ::account::ReqSignin& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::Resp>>(AsyncSigninRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::Resp>> PrepareAsyncSignin(::grpc::ClientContext* context, const ::account::ReqSignin& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::Resp>>(PrepareAsyncSigninRaw(context, request, cq));
    }
    ::grpc::Status Signup(::grpc::ClientContext* context, const ::account::ReqSignup& request, ::account::Resp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::Resp>> AsyncSignup(::grpc::ClientContext* context, const ::account::ReqSignup& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::Resp>>(AsyncSignupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::Resp>> PrepareAsyncSignup(::grpc::ClientContext* context, const ::account::ReqSignup& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::Resp>>(PrepareAsyncSignupRaw(context, request, cq));
    }
    ::grpc::Status VerifyCode(::grpc::ClientContext* context, const ::account::Reqverifycode& request, ::account::Resp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::Resp>> AsyncVerifyCode(::grpc::ClientContext* context, const ::account::Reqverifycode& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::Resp>>(AsyncVerifyCodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::Resp>> PrepareAsyncVerifyCode(::grpc::ClientContext* context, const ::account::Reqverifycode& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::Resp>>(PrepareAsyncVerifyCodeRaw(context, request, cq));
    }
    ::grpc::Status Userinfo(::grpc::ClientContext* context, const ::account::ReqUserinfo& request, ::account::Resp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::Resp>> AsyncUserinfo(::grpc::ClientContext* context, const ::account::ReqUserinfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::Resp>>(AsyncUserinfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::Resp>> PrepareAsyncUserinfo(::grpc::ClientContext* context, const ::account::ReqUserinfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::Resp>>(PrepareAsyncUserinfoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Signin(::grpc::ClientContext* context, const ::account::ReqSignin* request, ::account::Resp* response, std::function<void(::grpc::Status)>) override;
      void Signin(::grpc::ClientContext* context, const ::account::ReqSignin* request, ::account::Resp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Signup(::grpc::ClientContext* context, const ::account::ReqSignup* request, ::account::Resp* response, std::function<void(::grpc::Status)>) override;
      void Signup(::grpc::ClientContext* context, const ::account::ReqSignup* request, ::account::Resp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void VerifyCode(::grpc::ClientContext* context, const ::account::Reqverifycode* request, ::account::Resp* response, std::function<void(::grpc::Status)>) override;
      void VerifyCode(::grpc::ClientContext* context, const ::account::Reqverifycode* request, ::account::Resp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Userinfo(::grpc::ClientContext* context, const ::account::ReqUserinfo* request, ::account::Resp* response, std::function<void(::grpc::Status)>) override;
      void Userinfo(::grpc::ClientContext* context, const ::account::ReqUserinfo* request, ::account::Resp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::account::Resp>* AsyncSigninRaw(::grpc::ClientContext* context, const ::account::ReqSignin& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::Resp>* PrepareAsyncSigninRaw(::grpc::ClientContext* context, const ::account::ReqSignin& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::Resp>* AsyncSignupRaw(::grpc::ClientContext* context, const ::account::ReqSignup& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::Resp>* PrepareAsyncSignupRaw(::grpc::ClientContext* context, const ::account::ReqSignup& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::Resp>* AsyncVerifyCodeRaw(::grpc::ClientContext* context, const ::account::Reqverifycode& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::Resp>* PrepareAsyncVerifyCodeRaw(::grpc::ClientContext* context, const ::account::Reqverifycode& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::Resp>* AsyncUserinfoRaw(::grpc::ClientContext* context, const ::account::ReqUserinfo& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::Resp>* PrepareAsyncUserinfoRaw(::grpc::ClientContext* context, const ::account::ReqUserinfo& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Signin_;
    const ::grpc::internal::RpcMethod rpcmethod_Signup_;
    const ::grpc::internal::RpcMethod rpcmethod_VerifyCode_;
    const ::grpc::internal::RpcMethod rpcmethod_Userinfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Signin(::grpc::ServerContext* context, const ::account::ReqSignin* request, ::account::Resp* response);
    virtual ::grpc::Status Signup(::grpc::ServerContext* context, const ::account::ReqSignup* request, ::account::Resp* response);
    virtual ::grpc::Status VerifyCode(::grpc::ServerContext* context, const ::account::Reqverifycode* request, ::account::Resp* response);
    virtual ::grpc::Status Userinfo(::grpc::ServerContext* context, const ::account::ReqUserinfo* request, ::account::Resp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Signin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Signin() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Signin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Signin(::grpc::ServerContext* /*context*/, const ::account::ReqSignin* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSignin(::grpc::ServerContext* context, ::account::ReqSignin* request, ::grpc::ServerAsyncResponseWriter< ::account::Resp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Signup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Signup() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Signup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Signup(::grpc::ServerContext* /*context*/, const ::account::ReqSignup* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSignup(::grpc::ServerContext* context, ::account::ReqSignup* request, ::grpc::ServerAsyncResponseWriter< ::account::Resp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_VerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_VerifyCode() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_VerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyCode(::grpc::ServerContext* /*context*/, const ::account::Reqverifycode* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifyCode(::grpc::ServerContext* context, ::account::Reqverifycode* request, ::grpc::ServerAsyncResponseWriter< ::account::Resp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Userinfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Userinfo() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_Userinfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Userinfo(::grpc::ServerContext* /*context*/, const ::account::ReqUserinfo* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUserinfo(::grpc::ServerContext* context, ::account::ReqUserinfo* request, ::grpc::ServerAsyncResponseWriter< ::account::Resp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Signin<WithAsyncMethod_Signup<WithAsyncMethod_VerifyCode<WithAsyncMethod_Userinfo<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Signin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Signin() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::account::ReqSignin, ::account::Resp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::account::ReqSignin* request, ::account::Resp* response) { return this->Signin(context, request, response); }));}
    void SetMessageAllocatorFor_Signin(
        ::grpc::MessageAllocator< ::account::ReqSignin, ::account::Resp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::account::ReqSignin, ::account::Resp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Signin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Signin(::grpc::ServerContext* /*context*/, const ::account::ReqSignin* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Signin(
      ::grpc::CallbackServerContext* /*context*/, const ::account::ReqSignin* /*request*/, ::account::Resp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Signup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Signup() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::account::ReqSignup, ::account::Resp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::account::ReqSignup* request, ::account::Resp* response) { return this->Signup(context, request, response); }));}
    void SetMessageAllocatorFor_Signup(
        ::grpc::MessageAllocator< ::account::ReqSignup, ::account::Resp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::account::ReqSignup, ::account::Resp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Signup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Signup(::grpc::ServerContext* /*context*/, const ::account::ReqSignup* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Signup(
      ::grpc::CallbackServerContext* /*context*/, const ::account::ReqSignup* /*request*/, ::account::Resp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_VerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_VerifyCode() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::account::Reqverifycode, ::account::Resp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::account::Reqverifycode* request, ::account::Resp* response) { return this->VerifyCode(context, request, response); }));}
    void SetMessageAllocatorFor_VerifyCode(
        ::grpc::MessageAllocator< ::account::Reqverifycode, ::account::Resp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::account::Reqverifycode, ::account::Resp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_VerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyCode(::grpc::ServerContext* /*context*/, const ::account::Reqverifycode* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VerifyCode(
      ::grpc::CallbackServerContext* /*context*/, const ::account::Reqverifycode* /*request*/, ::account::Resp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Userinfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Userinfo() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::account::ReqUserinfo, ::account::Resp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::account::ReqUserinfo* request, ::account::Resp* response) { return this->Userinfo(context, request, response); }));}
    void SetMessageAllocatorFor_Userinfo(
        ::grpc::MessageAllocator< ::account::ReqUserinfo, ::account::Resp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::account::ReqUserinfo, ::account::Resp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Userinfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Userinfo(::grpc::ServerContext* /*context*/, const ::account::ReqUserinfo* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Userinfo(
      ::grpc::CallbackServerContext* /*context*/, const ::account::ReqUserinfo* /*request*/, ::account::Resp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Signin<WithCallbackMethod_Signup<WithCallbackMethod_VerifyCode<WithCallbackMethod_Userinfo<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Signin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Signin() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Signin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Signin(::grpc::ServerContext* /*context*/, const ::account::ReqSignin* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Signup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Signup() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Signup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Signup(::grpc::ServerContext* /*context*/, const ::account::ReqSignup* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_VerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_VerifyCode() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_VerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyCode(::grpc::ServerContext* /*context*/, const ::account::Reqverifycode* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Userinfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Userinfo() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_Userinfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Userinfo(::grpc::ServerContext* /*context*/, const ::account::ReqUserinfo* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Signin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Signin() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Signin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Signin(::grpc::ServerContext* /*context*/, const ::account::ReqSignin* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSignin(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Signup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Signup() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Signup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Signup(::grpc::ServerContext* /*context*/, const ::account::ReqSignup* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSignup(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_VerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_VerifyCode() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_VerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyCode(::grpc::ServerContext* /*context*/, const ::account::Reqverifycode* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifyCode(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Userinfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Userinfo() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_Userinfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Userinfo(::grpc::ServerContext* /*context*/, const ::account::ReqUserinfo* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUserinfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Signin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Signin() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Signin(context, request, response); }));
    }
    ~WithRawCallbackMethod_Signin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Signin(::grpc::ServerContext* /*context*/, const ::account::ReqSignin* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Signin(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Signup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Signup() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Signup(context, request, response); }));
    }
    ~WithRawCallbackMethod_Signup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Signup(::grpc::ServerContext* /*context*/, const ::account::ReqSignup* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Signup(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_VerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_VerifyCode() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->VerifyCode(context, request, response); }));
    }
    ~WithRawCallbackMethod_VerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyCode(::grpc::ServerContext* /*context*/, const ::account::Reqverifycode* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VerifyCode(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Userinfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Userinfo() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Userinfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_Userinfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Userinfo(::grpc::ServerContext* /*context*/, const ::account::ReqUserinfo* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Userinfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Signin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Signin() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::account::ReqSignin, ::account::Resp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::account::ReqSignin, ::account::Resp>* streamer) {
                       return this->StreamedSignin(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Signin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Signin(::grpc::ServerContext* /*context*/, const ::account::ReqSignin* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSignin(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::account::ReqSignin,::account::Resp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Signup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Signup() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::account::ReqSignup, ::account::Resp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::account::ReqSignup, ::account::Resp>* streamer) {
                       return this->StreamedSignup(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Signup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Signup(::grpc::ServerContext* /*context*/, const ::account::ReqSignup* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSignup(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::account::ReqSignup,::account::Resp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_VerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_VerifyCode() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::account::Reqverifycode, ::account::Resp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::account::Reqverifycode, ::account::Resp>* streamer) {
                       return this->StreamedVerifyCode(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_VerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status VerifyCode(::grpc::ServerContext* /*context*/, const ::account::Reqverifycode* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedVerifyCode(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::account::Reqverifycode,::account::Resp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Userinfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Userinfo() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::account::ReqUserinfo, ::account::Resp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::account::ReqUserinfo, ::account::Resp>* streamer) {
                       return this->StreamedUserinfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Userinfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Userinfo(::grpc::ServerContext* /*context*/, const ::account::ReqUserinfo* /*request*/, ::account::Resp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUserinfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::account::ReqUserinfo,::account::Resp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Signin<WithStreamedUnaryMethod_Signup<WithStreamedUnaryMethod_VerifyCode<WithStreamedUnaryMethod_Userinfo<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Signin<WithStreamedUnaryMethod_Signup<WithStreamedUnaryMethod_VerifyCode<WithStreamedUnaryMethod_Userinfo<Service > > > > StreamedService;
};

}  // namespace account


#endif  // GRPC_account_2eproto__INCLUDED
