// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: proto/storage_control/storage_control.proto

package storagecontrolpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitiateMultipartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateMultipartReq) Reset() {
	*x = InitiateMultipartReq{}
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateMultipartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMultipartReq) ProtoMessage() {}

func (x *InitiateMultipartReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMultipartReq.ProtoReflect.Descriptor instead.
func (*InitiateMultipartReq) Descriptor() ([]byte, []int) {
	return file_proto_storage_control_storage_control_proto_rawDescGZIP(), []int{0}
}

func (x *InitiateMultipartReq) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *InitiateMultipartReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *InitiateMultipartReq) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type InitiateMultipartResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StorageUploadId string                 `protobuf:"bytes,1,opt,name=storage_upload_id,json=storageUploadId,proto3" json:"storage_upload_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitiateMultipartResp) Reset() {
	*x = InitiateMultipartResp{}
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateMultipartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMultipartResp) ProtoMessage() {}

func (x *InitiateMultipartResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMultipartResp.ProtoReflect.Descriptor instead.
func (*InitiateMultipartResp) Descriptor() ([]byte, []int) {
	return file_proto_storage_control_storage_control_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateMultipartResp) GetStorageUploadId() string {
	if x != nil {
		return x.StorageUploadId
	}
	return ""
}

type PresignPartReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey       string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	StorageUploadId string                 `protobuf:"bytes,2,opt,name=storage_upload_id,json=storageUploadId,proto3" json:"storage_upload_id,omitempty"`
	PartNumber      int32                  `protobuf:"varint,3,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	ExpiresSeconds  int64                  `protobuf:"varint,4,opt,name=expires_seconds,json=expiresSeconds,proto3" json:"expires_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PresignPartReq) Reset() {
	*x = PresignPartReq{}
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignPartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignPartReq) ProtoMessage() {}

func (x *PresignPartReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignPartReq.ProtoReflect.Descriptor instead.
func (*PresignPartReq) Descriptor() ([]byte, []int) {
	return file_proto_storage_control_storage_control_proto_rawDescGZIP(), []int{2}
}

func (x *PresignPartReq) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *PresignPartReq) GetStorageUploadId() string {
	if x != nil {
		return x.StorageUploadId
	}
	return ""
}

func (x *PresignPartReq) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *PresignPartReq) GetExpiresSeconds() int64 {
	if x != nil {
		return x.ExpiresSeconds
	}
	return 0
}

type PresignPartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignPartResp) Reset() {
	*x = PresignPartResp{}
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignPartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignPartResp) ProtoMessage() {}

func (x *PresignPartResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignPartResp.ProtoReflect.Descriptor instead.
func (*PresignPartResp) Descriptor() ([]byte, []int) {
	return file_proto_storage_control_storage_control_proto_rawDescGZIP(), []int{3}
}

func (x *PresignPartResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PresignPartResp) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type UploadedPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartNumber    int32                  `protobuf:"varint,1,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadedPart) Reset() {
	*x = UploadedPart{}
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadedPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadedPart) ProtoMessage() {}

func (x *UploadedPart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadedPart.ProtoReflect.Descriptor instead.
func (*UploadedPart) Descriptor() ([]byte, []int) {
	return file_proto_storage_control_storage_control_proto_rawDescGZIP(), []int{4}
}

func (x *UploadedPart) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *UploadedPart) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type ListPartsReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey       string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	StorageUploadId string                 `protobuf:"bytes,2,opt,name=storage_upload_id,json=storageUploadId,proto3" json:"storage_upload_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListPartsReq) Reset() {
	*x = ListPartsReq{}
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartsReq) ProtoMessage() {}

func (x *ListPartsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartsReq.ProtoReflect.Descriptor instead.
func (*ListPartsReq) Descriptor() ([]byte, []int) {
	return file_proto_storage_control_storage_control_proto_rawDescGZIP(), []int{5}
}

func (x *ListPartsReq) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ListPartsReq) GetStorageUploadId() string {
	if x != nil {
		return x.StorageUploadId
	}
	return ""
}

type ListPartsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parts         []*UploadedPart        `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartsResp) Reset() {
	*x = ListPartsResp{}
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartsResp) ProtoMessage() {}

func (x *ListPartsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartsResp.ProtoReflect.Descriptor instead.
func (*ListPartsResp) Descriptor() ([]byte, []int) {
	return file_proto_storage_control_storage_control_proto_rawDescGZIP(), []int{6}
}

func (x *ListPartsResp) GetParts() []*UploadedPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

type CompleteMultipartReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey       string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	StorageUploadId string                 `protobuf:"bytes,2,opt,name=storage_upload_id,json=storageUploadId,proto3" json:"storage_upload_id,omitempty"`
	ContentType     string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Parts           []*UploadedPart        `protobuf:"bytes,4,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompleteMultipartReq) Reset() {
	*x = CompleteMultipartReq{}
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMultipartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMultipartReq) ProtoMessage() {}

func (x *CompleteMultipartReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMultipartReq.ProtoReflect.Descriptor instead.
func (*CompleteMultipartReq) Descriptor() ([]byte, []int) {
	return file_proto_storage_control_storage_control_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteMultipartReq) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *CompleteMultipartReq) GetStorageUploadId() string {
	if x != nil {
		return x.StorageUploadId
	}
	return ""
}

func (x *CompleteMultipartReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CompleteMultipartReq) GetParts() []*UploadedPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

type CompleteMultipartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMultipartResp) Reset() {
	*x = CompleteMultipartResp{}
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMultipartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMultipartResp) ProtoMessage() {}

func (x *CompleteMultipartResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMultipartResp.ProtoReflect.Descriptor instead.
func (*CompleteMultipartResp) Descriptor() ([]byte, []int) {
	return file_proto_storage_control_storage_control_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteMultipartResp) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *CompleteMultipartResp) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type AbortMultipartReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey       string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	StorageUploadId string                 `protobuf:"bytes,2,opt,name=storage_upload_id,json=storageUploadId,proto3" json:"storage_upload_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AbortMultipartReq) Reset() {
	*x = AbortMultipartReq{}
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortMultipartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortMultipartReq) ProtoMessage() {}

func (x *AbortMultipartReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortMultipartReq.ProtoReflect.Descriptor instead.
func (*AbortMultipartReq) Descriptor() ([]byte, []int) {
	return file_proto_storage_control_storage_control_proto_rawDescGZIP(), []int{9}
}

func (x *AbortMultipartReq) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *AbortMultipartReq) GetStorageUploadId() string {
	if x != nil {
		return x.StorageUploadId
	}
	return ""
}

type AbortMultipartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortMultipartResp) Reset() {
	*x = AbortMultipartResp{}
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortMultipartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortMultipartResp) ProtoMessage() {}

func (x *AbortMultipartResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortMultipartResp.ProtoReflect.Descriptor instead.
func (*AbortMultipartResp) Descriptor() ([]byte, []int) {
	return file_proto_storage_control_storage_control_proto_rawDescGZIP(), []int{10}
}

type PresignGetReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey         string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Filename          string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType       string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	InlineDisposition bool                   `protobuf:"varint,4,opt,name=inline_disposition,json=inlineDisposition,proto3" json:"inline_disposition,omitempty"`
	ExpiresSeconds    int64                  `protobuf:"varint,5,opt,name=expires_seconds,json=expiresSeconds,proto3" json:"expires_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PresignGetReq) Reset() {
	*x = PresignGetReq{}
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignGetReq) ProtoMessage() {}

func (x *PresignGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignGetReq.ProtoReflect.Descriptor instead.
func (*PresignGetReq) Descriptor() ([]byte, []int) {
	return file_proto_storage_control_storage_control_proto_rawDescGZIP(), []int{11}
}

func (x *PresignGetReq) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *PresignGetReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *PresignGetReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PresignGetReq) GetInlineDisposition() bool {
	if x != nil {
		return x.InlineDisposition
	}
	return false
}

func (x *PresignGetReq) GetExpiresSeconds() int64 {
	if x != nil {
		return x.ExpiresSeconds
	}
	return 0
}

type PresignGetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignGetResp) Reset() {
	*x = PresignGetResp{}
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignGetResp) ProtoMessage() {}

func (x *PresignGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignGetResp.ProtoReflect.Descriptor instead.
func (*PresignGetResp) Descriptor() ([]byte, []int) {
	return file_proto_storage_control_storage_control_proto_rawDescGZIP(), []int{12}
}

func (x *PresignGetResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type HeadObjectReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadObjectReq) Reset() {
	*x = HeadObjectReq{}
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadObjectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadObjectReq) ProtoMessage() {}

func (x *HeadObjectReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadObjectReq.ProtoReflect.Descriptor instead.
func (*HeadObjectReq) Descriptor() ([]byte, []int) {
	return file_proto_storage_control_storage_control_proto_rawDescGZIP(), []int{13}
}

func (x *HeadObjectReq) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

type HeadObjectResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Etag          string                 `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadObjectResp) Reset() {
	*x = HeadObjectResp{}
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadObjectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadObjectResp) ProtoMessage() {}

func (x *HeadObjectResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_control_storage_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadObjectResp.ProtoReflect.Descriptor instead.
func (*HeadObjectResp) Descriptor() ([]byte, []int) {
	return file_proto_storage_control_storage_control_proto_rawDescGZIP(), []int{14}
}

func (x *HeadObjectResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *HeadObjectResp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *HeadObjectResp) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *HeadObjectResp) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_proto_storage_control_storage_control_proto protoreflect.FileDescriptor

const file_proto_storage_control_storage_control_proto_rawDesc = "" +
	"\n" +
	"+proto/storage_control/storage_control.proto\x12\x0fstorage_control\"\xe6\x01\n" +
	"\x14InitiateMultipartReq\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12O\n" +
	"\bmetadata\x18\x03 \x03(\v23.storage_control.InitiateMultipartReq.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x15InitiateMultipartResp\x12*\n" +
	"\x11storage_upload_id\x18\x01 \x01(\tR\x0fstorageUploadId\"\xa5\x01\n" +
	"\x0ePresignPartReq\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12*\n" +
	"\x11storage_upload_id\x18\x02 \x01(\tR\x0fstorageUploadId\x12\x1f\n" +
	"\vpart_number\x18\x03 \x01(\x05R\n" +
	"partNumber\x12'\n" +
	"\x0fexpires_seconds\x18\x04 \x01(\x03R\x0eexpiresSeconds\"B\n" +
	"\x0fPresignPartResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\"C\n" +
	"\fUploadedPart\x12\x1f\n" +
	"\vpart_number\x18\x01 \x01(\x05R\n" +
	"partNumber\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\"Y\n" +
	"\fListPartsReq\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12*\n" +
	"\x11storage_upload_id\x18\x02 \x01(\tR\x0fstorageUploadId\"D\n" +
	"\rListPartsResp\x123\n" +
	"\x05parts\x18\x01 \x03(\v2\x1d.storage_control.UploadedPartR\x05parts\"\xb9\x01\n" +
	"\x14CompleteMultipartReq\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12*\n" +
	"\x11storage_upload_id\x18\x02 \x01(\tR\x0fstorageUploadId\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x123\n" +
	"\x05parts\x18\x04 \x03(\v2\x1d.storage_control.UploadedPartR\x05parts\"J\n" +
	"\x15CompleteMultipartResp\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\"^\n" +
	"\x11AbortMultipartReq\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12*\n" +
	"\x11storage_upload_id\x18\x02 \x01(\tR\x0fstorageUploadId\"\x14\n" +
	"\x12AbortMultipartResp\"\xc5\x01\n" +
	"\rPresignGetReq\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12-\n" +
	"\x12inline_disposition\x18\x04 \x01(\bR\x11inlineDisposition\x12'\n" +
	"\x0fexpires_seconds\x18\x05 \x01(\x03R\x0eexpiresSeconds\"\"\n" +
	"\x0ePresignGetResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\".\n" +
	"\rHeadObjectReq\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\"s\n" +
	"\x0eHeadObjectResp\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04etag\x18\x03 \x01(\tR\x04etag\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType2\xef\x04\n" +
	"\x0eStorageControl\x12b\n" +
	"\x11InitiateMultipart\x12%.storage_control.InitiateMultipartReq\x1a&.storage_control.InitiateMultipartResp\x12P\n" +
	"\vPresignPart\x12\x1f.storage_control.PresignPartReq\x1a .storage_control.PresignPartResp\x12J\n" +
	"\tListParts\x12\x1d.storage_control.ListPartsReq\x1a\x1e.storage_control.ListPartsResp\x12b\n" +
	"\x11CompleteMultipart\x12%.storage_control.CompleteMultipartReq\x1a&.storage_control.CompleteMultipartResp\x12Y\n" +
	"\x0eAbortMultipart\x12\".storage_control.AbortMultipartReq\x1a#.storage_control.AbortMultipartResp\x12M\n" +
	"\n" +
	"PresignGet\x12\x1e.storage_control.PresignGetReq\x1a\x1f.storage_control.PresignGetResp\x12M\n" +
	"\n" +
	"HeadObject\x12\x1e.storage_control.HeadObjectReq\x1a\x1f.storage_control.HeadObjectRespB8Z6clouddisk_v2/storage_control/protobuf;storagecontrolpbb\x06proto3"

var (
	file_proto_storage_control_storage_control_proto_rawDescOnce sync.Once
	file_proto_storage_control_storage_control_proto_rawDescData []byte
)

func file_proto_storage_control_storage_control_proto_rawDescGZIP() []byte {
	file_proto_storage_control_storage_control_proto_rawDescOnce.Do(func() {
		file_proto_storage_control_storage_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_storage_control_storage_control_proto_rawDesc), len(file_proto_storage_control_storage_control_proto_rawDesc)))
	})
	return file_proto_storage_control_storage_control_proto_rawDescData
}

var file_proto_storage_control_storage_control_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_storage_control_storage_control_proto_goTypes = []any{
	(*InitiateMultipartReq)(nil),  // 0: storage_control.InitiateMultipartReq
	(*InitiateMultipartResp)(nil), // 1: storage_control.InitiateMultipartResp
	(*PresignPartReq)(nil),        // 2: storage_control.PresignPartReq
	(*PresignPartResp)(nil),       // 3: storage_control.PresignPartResp
	(*UploadedPart)(nil),          // 4: storage_control.UploadedPart
	(*ListPartsReq)(nil),          // 5: storage_control.ListPartsReq
	(*ListPartsResp)(nil),         // 6: storage_control.ListPartsResp
	(*CompleteMultipartReq)(nil),  // 7: storage_control.CompleteMultipartReq
	(*CompleteMultipartResp)(nil), // 8: storage_control.CompleteMultipartResp
	(*AbortMultipartReq)(nil),     // 9: storage_control.AbortMultipartReq
	(*AbortMultipartResp)(nil),    // 10: storage_control.AbortMultipartResp
	(*PresignGetReq)(nil),         // 11: storage_control.PresignGetReq
	(*PresignGetResp)(nil),        // 12: storage_control.PresignGetResp
	(*HeadObjectReq)(nil),         // 13: storage_control.HeadObjectReq
	(*HeadObjectResp)(nil),        // 14: storage_control.HeadObjectResp
	nil,                           // 15: storage_control.InitiateMultipartReq.MetadataEntry
}
var file_proto_storage_control_storage_control_proto_depIdxs = []int32{
	15, // 0: storage_control.InitiateMultipartReq.metadata:type_name -> storage_control.InitiateMultipartReq.MetadataEntry
	4,  // 1: storage_control.ListPartsResp.parts:type_name -> storage_control.UploadedPart
	4,  // 2: storage_control.CompleteMultipartReq.parts:type_name -> storage_control.UploadedPart
	0,  // 3: storage_control.StorageControl.InitiateMultipart:input_type -> storage_control.InitiateMultipartReq
	2,  // 4: storage_control.StorageControl.PresignPart:input_type -> storage_control.PresignPartReq
	5,  // 5: storage_control.StorageControl.ListParts:input_type -> storage_control.ListPartsReq
	7,  // 6: storage_control.StorageControl.CompleteMultipart:input_type -> storage_control.CompleteMultipartReq
	9,  // 7: storage_control.StorageControl.AbortMultipart:input_type -> storage_control.AbortMultipartReq
	11, // 8: storage_control.StorageControl.PresignGet:input_type -> storage_control.PresignGetReq
	13, // 9: storage_control.StorageControl.HeadObject:input_type -> storage_control.HeadObjectReq
	1,  // 10: storage_control.StorageControl.InitiateMultipart:output_type -> storage_control.InitiateMultipartResp
	3,  // 11: storage_control.StorageControl.PresignPart:output_type -> storage_control.PresignPartResp
	6,  // 12: storage_control.StorageControl.ListParts:output_type -> storage_control.ListPartsResp
	8,  // 13: storage_control.StorageControl.CompleteMultipart:output_type -> storage_control.CompleteMultipartResp
	10, // 14: storage_control.StorageControl.AbortMultipart:output_type -> storage_control.AbortMultipartResp
	12, // 15: storage_control.StorageControl.PresignGet:output_type -> storage_control.PresignGetResp
	14, // 16: storage_control.StorageControl.HeadObject:output_type -> storage_control.HeadObjectResp
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_storage_control_storage_control_proto_init() }
func file_proto_storage_control_storage_control_proto_init() {
	if File_proto_storage_control_storage_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_storage_control_storage_control_proto_rawDesc), len(file_proto_storage_control_storage_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_storage_control_storage_control_proto_goTypes,
		DependencyIndexes: file_proto_storage_control_storage_control_proto_depIdxs,
		MessageInfos:      file_proto_storage_control_storage_control_proto_msgTypes,
	}.Build()
	File_proto_storage_control_storage_control_proto = out.File
	file_proto_storage_control_storage_control_proto_goTypes = nil
	file_proto_storage_control_storage_control_proto_depIdxs = nil
}
