// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: proto/storage_control/storage_control.proto

package storagecontrolpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageControl_InitiateMultipart_FullMethodName = "/storage_control.StorageControl/InitiateMultipart"
	StorageControl_PresignPart_FullMethodName       = "/storage_control.StorageControl/PresignPart"
	StorageControl_ListParts_FullMethodName         = "/storage_control.StorageControl/ListParts"
	StorageControl_CompleteMultipart_FullMethodName = "/storage_control.StorageControl/CompleteMultipart"
	StorageControl_AbortMultipart_FullMethodName    = "/storage_control.StorageControl/AbortMultipart"
	StorageControl_PresignGet_FullMethodName        = "/storage_control.StorageControl/PresignGet"
	StorageControl_HeadObject_FullMethodName        = "/storage_control.StorageControl/HeadObject"
)

// StorageControlClient is the client API for StorageControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageControlClient interface {
	InitiateMultipart(ctx context.Context, in *InitiateMultipartReq, opts ...grpc.CallOption) (*InitiateMultipartResp, error)
	PresignPart(ctx context.Context, in *PresignPartReq, opts ...grpc.CallOption) (*PresignPartResp, error)
	ListParts(ctx context.Context, in *ListPartsReq, opts ...grpc.CallOption) (*ListPartsResp, error)
	CompleteMultipart(ctx context.Context, in *CompleteMultipartReq, opts ...grpc.CallOption) (*CompleteMultipartResp, error)
	AbortMultipart(ctx context.Context, in *AbortMultipartReq, opts ...grpc.CallOption) (*AbortMultipartResp, error)
	PresignGet(ctx context.Context, in *PresignGetReq, opts ...grpc.CallOption) (*PresignGetResp, error)
	HeadObject(ctx context.Context, in *HeadObjectReq, opts ...grpc.CallOption) (*HeadObjectResp, error)
}

type storageControlClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageControlClient(cc grpc.ClientConnInterface) StorageControlClient {
	return &storageControlClient{cc}
}

func (c *storageControlClient) InitiateMultipart(ctx context.Context, in *InitiateMultipartReq, opts ...grpc.CallOption) (*InitiateMultipartResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateMultipartResp)
	err := c.cc.Invoke(ctx, StorageControl_InitiateMultipart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageControlClient) PresignPart(ctx context.Context, in *PresignPartReq, opts ...grpc.CallOption) (*PresignPartResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresignPartResp)
	err := c.cc.Invoke(ctx, StorageControl_PresignPart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageControlClient) ListParts(ctx context.Context, in *ListPartsReq, opts ...grpc.CallOption) (*ListPartsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPartsResp)
	err := c.cc.Invoke(ctx, StorageControl_ListParts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageControlClient) CompleteMultipart(ctx context.Context, in *CompleteMultipartReq, opts ...grpc.CallOption) (*CompleteMultipartResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteMultipartResp)
	err := c.cc.Invoke(ctx, StorageControl_CompleteMultipart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageControlClient) AbortMultipart(ctx context.Context, in *AbortMultipartReq, opts ...grpc.CallOption) (*AbortMultipartResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortMultipartResp)
	err := c.cc.Invoke(ctx, StorageControl_AbortMultipart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageControlClient) PresignGet(ctx context.Context, in *PresignGetReq, opts ...grpc.CallOption) (*PresignGetResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresignGetResp)
	err := c.cc.Invoke(ctx, StorageControl_PresignGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageControlClient) HeadObject(ctx context.Context, in *HeadObjectReq, opts ...grpc.CallOption) (*HeadObjectResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeadObjectResp)
	err := c.cc.Invoke(ctx, StorageControl_HeadObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageControlServer is the server API for StorageControl service.
// All implementations must embed UnimplementedStorageControlServer
// for forward compatibility.
type StorageControlServer interface {
	InitiateMultipart(context.Context, *InitiateMultipartReq) (*InitiateMultipartResp, error)
	PresignPart(context.Context, *PresignPartReq) (*PresignPartResp, error)
	ListParts(context.Context, *ListPartsReq) (*ListPartsResp, error)
	CompleteMultipart(context.Context, *CompleteMultipartReq) (*CompleteMultipartResp, error)
	AbortMultipart(context.Context, *AbortMultipartReq) (*AbortMultipartResp, error)
	PresignGet(context.Context, *PresignGetReq) (*PresignGetResp, error)
	HeadObject(context.Context, *HeadObjectReq) (*HeadObjectResp, error)
	mustEmbedUnimplementedStorageControlServer()
}

// UnimplementedStorageControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageControlServer struct{}

func (UnimplementedStorageControlServer) InitiateMultipart(context.Context, *InitiateMultipartReq) (*InitiateMultipartResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateMultipart not implemented")
}
func (UnimplementedStorageControlServer) PresignPart(context.Context, *PresignPartReq) (*PresignPartResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PresignPart not implemented")
}
func (UnimplementedStorageControlServer) ListParts(context.Context, *ListPartsReq) (*ListPartsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListParts not implemented")
}
func (UnimplementedStorageControlServer) CompleteMultipart(context.Context, *CompleteMultipartReq) (*CompleteMultipartResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteMultipart not implemented")
}
func (UnimplementedStorageControlServer) AbortMultipart(context.Context, *AbortMultipartReq) (*AbortMultipartResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortMultipart not implemented")
}
func (UnimplementedStorageControlServer) PresignGet(context.Context, *PresignGetReq) (*PresignGetResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PresignGet not implemented")
}
func (UnimplementedStorageControlServer) HeadObject(context.Context, *HeadObjectReq) (*HeadObjectResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeadObject not implemented")
}
func (UnimplementedStorageControlServer) mustEmbedUnimplementedStorageControlServer() {}
func (UnimplementedStorageControlServer) testEmbeddedByValue()                        {}

// UnsafeStorageControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageControlServer will
// result in compilation errors.
type UnsafeStorageControlServer interface {
	mustEmbedUnimplementedStorageControlServer()
}

func RegisterStorageControlServer(s grpc.ServiceRegistrar, srv StorageControlServer) {
	// If the following call pancis, it indicates UnimplementedStorageControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageControl_ServiceDesc, srv)
}

func _StorageControl_InitiateMultipart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateMultipartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageControlServer).InitiateMultipart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageControl_InitiateMultipart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageControlServer).InitiateMultipart(ctx, req.(*InitiateMultipartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageControl_PresignPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresignPartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageControlServer).PresignPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageControl_PresignPart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageControlServer).PresignPart(ctx, req.(*PresignPartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageControl_ListParts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPartsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageControlServer).ListParts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageControl_ListParts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageControlServer).ListParts(ctx, req.(*ListPartsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageControl_CompleteMultipart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteMultipartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageControlServer).CompleteMultipart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageControl_CompleteMultipart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageControlServer).CompleteMultipart(ctx, req.(*CompleteMultipartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageControl_AbortMultipart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortMultipartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageControlServer).AbortMultipart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageControl_AbortMultipart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageControlServer).AbortMultipart(ctx, req.(*AbortMultipartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageControl_PresignGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresignGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageControlServer).PresignGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageControl_PresignGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageControlServer).PresignGet(ctx, req.(*PresignGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageControl_HeadObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeadObjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageControlServer).HeadObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageControl_HeadObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageControlServer).HeadObject(ctx, req.(*HeadObjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageControl_ServiceDesc is the grpc.ServiceDesc for StorageControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage_control.StorageControl",
	HandlerType: (*StorageControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateMultipart",
			Handler:    _StorageControl_InitiateMultipart_Handler,
		},
		{
			MethodName: "PresignPart",
			Handler:    _StorageControl_PresignPart_Handler,
		},
		{
			MethodName: "ListParts",
			Handler:    _StorageControl_ListParts_Handler,
		},
		{
			MethodName: "CompleteMultipart",
			Handler:    _StorageControl_CompleteMultipart_Handler,
		},
		{
			MethodName: "AbortMultipart",
			Handler:    _StorageControl_AbortMultipart_Handler,
		},
		{
			MethodName: "PresignGet",
			Handler:    _StorageControl_PresignGet_Handler,
		},
		{
			MethodName: "HeadObject",
			Handler:    _StorageControl_HeadObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/storage_control/storage_control.proto",
}
